</div>
</div>
</div>

<div class="ui small modal canfirmar" id="modalConfimar">
  <i class="close icon"></i>
  <div class="header">
    Confirmação
  </div>
  <div class="content" id="msgConfirmacao"> 
  </div>
  <div class="actions">
    <div class="ui positive labled icon button">
      <i class="ui thumbs up icon"></i>
      Sim
    </div>    
    <div class="ui negative labled icon button">
      <i class="ui thumbs down icon"></i>
      Não
    </div>
  </div>
</div>

 </div>

</body>
</html>