<?php 

  $niveis = '';
  foreach ($dados['niveis'] as $id => $nivel)
    $niveis .= "<option value='" . $nivel['id'] ."'>" . $nivel['nivel'] . "</option>"; 

  $grauformacao = '';
  foreach ($dados['grauformacao'] as $id => $grau)
    $grauformacao .= "<option value='" . $grau['id'] ."'>" . $grau['grau'] . "</option>";  

  $areasformacao = '';
  foreach ($dados['areasformacao'] as $id => $grau)
    $areasformacao .= "<option value='" . $grau['id'] ."'>" . $grau['areaformacao'] . "</option>";    

  $segmentos = '';
  foreach ($dados['segmentos'] as $id => $segmento)
    $segmentos .= "<option value='" . $segmento['id'] ."'>" . $segmento['segmento'] . "</option>";  

  $cargos = '';
  foreach ($dados['cargos'] as $id => $cargo)
    $cargos .= "<option value='" . $cargo['id'] ."'>" . $cargo['cargo'] . "</option>";  
  
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<title>Cadastro de Currículos</title>

<link href="<?php echo URL; ?>public/css/estiloNovo.css" rel="stylesheet" type="text/css" />
<link href='http://fonts.googleapis.com/css?family=Alegreya+Sans' rel='stylesheet' type='text/css'>

<link href="<?php echo URL; ?>public/css/estiloPaginaNovo.css" rel="stylesheet" type="text/css" />
<link rel="shortcut icon" href="<?php echo URL; ?>favicon.ico" type="image/x-icon" />

<script src="<?php echo URL; ?>public/js/valid.js"></script>
<script type="text/javascript" src="<?php echo URL; ?>public/js/jquery.js"></script>


<script type="text/javascript">

function confirmar(id) {

	$('.telaConfirma').fadeIn(500);

}



function carregar(acao) {
	if(acao == "abrir"){
		$('.confirmaFundo').fadeIn(500);
	}else{
		$('.telaConfirma').fadeOut(500);
		$('.confirmaFundo').fadeOut(500);
	}
}



$(document).keydown(function(event) { // caso seja precionado ESC chama mostrarLogin('0')
        if (event.keyCode == 27) 
			mostrarLogin('0');
    });



function mostrarLogin(acao){
	if(acao == "1")
		$('.mascara').fadeIn(400);
	else
		$('.mascara').fadeOut(400);
}

</script>

<script type="text/javascript">

function verificarLogin() {
	var x = document.getElementById('email2');
	$.post('verificarLogin.php', { login: x.value },
		function(output) {
			$('#retorno').html(output).fadeIn(1000);
		});

}



function mostrarSubmit() {

	$('#submit').fadeIn(200);

	$('#verlogin').fadeOut(200);

}

function esconderSubmit() {

  /*
	$('#submit').fadeOut(200);

	$('#retorno').fadeOut(200);

	$('#verlogin').fadeIn(200);
  */
}



</script>



</head>

<body>

<!--bloco para confirmação de cadastro de curriculo ou empresa-->


<div class="confirmaFundo" style="display:none"><div id="loading">

</div></div>

<!--bloco para confirmação de cadastro de curriculo ou empresa-->



<div class="topo">
<div class="topoinner">


<div class="menu">
<div class="menuinner">
<a href="<?php echo URL; ?>"><img src="<?php echo URL; ?>public/images/titulo.png" width="344" height="65" border="0" /></a><br />
<div>
<a href="<?php echo URL; ?>">Página Incial&nbsp;&nbsp;|</a><a href="<?php echo URL; ?>comofunciona/">&nbsp;&nbsp;Como Funciona</a>
</div>
</div>
<!--LOGIN-->

<!--FINAL DO LOGIN-->


</div>

</div>
<div class="transparente"></div>
</div>

<div class="sombra"></div>
<div class="conteudo">

	






<script src="<?php echo URL; ?>public/js/SpryAssets/SpryValidationTextField.js" type="text/javascript"></script>
<!-- <script src="<?php echo URL; ?>public/js/jquery.js" type="text/javascript"></script> -->
<script type="text/javascript" src="<?php echo URL; ?>public/js/jquery.maskedinput.min.js"></script>
<!-- <script src="<?php echo URL; ?>public/js/jquery-mask.min.1.6.1.js" type="text/javascript"></script> -->


<script src="<?php echo URL; ?>public/js/novosTratamentosCadAdm.js" type="text/javascript"></script>


<link href="<?php echo URL; ?>/SpryAssets/SpryValidationTextField.css" rel="stylesheet" type="text/css" />



<script src="<?php echo URL; ?>/SpryAssets/SpryValidationRadio.js" type="text/javascript"></script>

<script src="<?php echo URL; ?>/SpryAssets/SpryValidationSelect.js" type="text/javascript"></script>

<link href="<?php echo URL; ?>/SpryAssets/SpryValidationRadio.css" rel="stylesheet" type="text/css" />



<link href="<?php echo URL; ?>/SpryAssets/SpryValidationSelect.css" rel="stylesheet" type="text/css" />



<script type="text/javascript">



	function verSenha(){



		if (document.formCadCurriculo.senha.value != document.formCadCurriculo.senha2.value) {



			alert('As senhas não conferem');	



		}



	}



</script>














<div class="barra">

  <h3 id="cadCurriculo">Cadastrando novo Currículo</h3>



</div>




* Campos de preenchimento obrigatório







<form id="formCadCurriculo" name="formCadCurriculo" method="post" action="" class="formulario" enctype="multipart/form-data">



  



  <h2>Dados Pessoais<strong><a name="trocaEmail" id="trocaEmail"></a></strong></h2>



  



  <table width="100%" border="0" cellpadding="2" cellspacing="1" class="bloco">



    <tr>



      <td width="27%" align="right" bgcolor="#F3F3F3"><strong>*Nome completo</strong></td>



      <td width="73%" bgcolor="#FFFFFF"><label for="nome"></label>



        <span id="nomecampleto">



        <input type="text" name="nome" id="nome" style="width:400px"/>



      <span class="textfieldRequiredMsg">digite seu nome.</span></span></td>



    </tr>



    <tr>



      <td align="right" bgcolor="#F3F3F3"><strong>*E-mail</strong></td>



      <td bgcolor="#FFFFFF"><span id="sprytextfield2">



      <input type="text" name="email" id="email" style="width:400px" onchange="pegaEmail()" onfocus="esconderSubmit()" />



      <span class="textfieldRequiredMsg">Digite seu e-mail.</span><span class="textfieldInvalidFormatMsg" id="email1">Formato Inválido.</span></span></td>



    </tr>

 <tr>



      <td align="right" bgcolor="#F3F3F3">Facebook</td>



      <td bgcolor="#FFFFFF"><span id="facebook">



      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;https://www.facebook.com/<input type="text" name="facebook" id="faceCampo" style="width:200px"/>



     <span class="textfieldInvalidFormatMsg">Esta conta não existe.</span></span></td>


   </tr>
   <tr>
      <td align="right" bgcolor="#F3F3F3">Selecione uma foto sua</td>
      <td bgcolor="#FFFFFF">
        <input type='file' name='foto' id='foto' />
        <span class="textfieldInvalidFormatMsg" id="mensagemFoto" style="color: #CC3333;"></span>
      </td>
   </tr>


    <tr>

      <td align="right" bgcolor="#F3F3F3"><strong>*CPF</strong></td>



      <td bgcolor="#FFFFFF"><span id="sprytextfield3">



      <input name="cpf" type="text" id="cpf" onblur="" maxlength="11"/>

<span class="textfieldInvalidFormatMsg" id="mensagemCpf">Cpf Inválido.</span><span class="textfieldRequiredMsg">Digite seu CPF.</span></span></td>



    </tr>


    <tr>
      <td align="right" bgcolor="#F3F3F3"><strong>*RG</strong></td>
      <td bgcolor="#FFFFFF"><span id="rgSpan">
      <input name="rg" type="text" id="rgCampo" onblur="" maxlength="20"/>
      <span class="textfieldInvalidFormatMsg" id="mensagemRg">RG Inválido.</span><span class="textfieldRequiredMsg">Digite seu RG.</span></span></td>
    </tr>

    <tr>
      <td width="27%" align="right" bgcolor="#F3F3F3"><strong>*Nome da Mãe</strong></td>
      <td width="73%" bgcolor="#FFFFFF"><label for="nome"></label>
        <span id="nomeMae">
        <input type="text" name="nomeMae" id="nomeMaeCampo" style="width:400px"/>
      <span class="textfieldRequiredMsg">Digite o nome da sua mãe.</span></span></td>
    </tr>    

    <tr>



      <td align="right" bgcolor="#F3F3F3"><strong>*Data de Nascimento</strong></td>



      <td bgcolor="#FFFFFF"><span id="sprytextfield4">



      <input type="text" name="dataNascimento" id="dataNascimento" onkeyup="DigitaData(this)" onblur="DigitaData(this)" />



      <span class="textfieldRequiredMsg">Digite sua data de nascimento.</span><span class="textfieldInvalidFormatMsg">Data Inválida.</span></span></td>



    </tr>



    <tr>



      <td align="right" bgcolor="#F3F3F3"><strong>*Sexo</strong></td>



      <td bgcolor="#FFFFFF"><label for="sexo"><span id="spryradio1">



          <input type="radio" name="sexo" value="masculino" id="sexoValida_0" /> 



          Masculino







<input type="radio" name="sexo" value="feminino" id="sexoValida_1" /> 



Feminino



<br />



<span class="radioRequiredMsg">Marque seu sexo.</span></span></label></td>



    </tr>



    <tr>



      <td align="right" bgcolor="#F3F3F3"><strong>*Estado Civil</strong></td>



      <td bgcolor="#FFFFFF"><label for="estado"></label>

        <span id="spryselect1">

        <select name="estadoCivil" id="estadoCivil">

          <option>Selecione</option>

          <option value="1">Casado</option>

          <option value="2">Solteiro</option>

          <option value="3">Divorciado</option>

          <option value="4">Viúvo</option>

        </select>

      <span class="selectRequiredMsg">Escolha seu estado civil.</span></span></td>



    </tr>


    <tr>
      <td align="right" bgcolor="#F3F3F3"><strong>*Quantidade de Filhos</strong></td>
          <td bgcolor="#FFFFFF">
            <span id="quantidadeFilhos">
              <select name="qtdFilhos"/>
                <option value=""></option>
                <option value="0">0</option>
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
                <option value="6">6</option>
                <option value="7">7</option>
                <option value="8">8</option>
                <option value="9">9</option>
                <option value="10">10</option>
                <option value="11">Mais</option>
              </select>
            <span class="selectRequiredMsg">Informe a quantidade de filhos</span></span>
        </td>
    </tr>  

    <tr>



      <td width="200" align="right" bgcolor="#F3F3F3"><strong>*CEP</strong></td>



      <td bgcolor="#FFFFFF"><span id="sprytextfield5">



      <input type="text" name="cep" id="cep" />



      <span class="textfieldRequiredMsg">Digite seu cep.</span></span> 



      <a href="http://www.buscacep.correios.com.br/servicos/dnec/menuAction.do?Metodo=menuEndereco" target="_blank">Esqueci meu cep</a></td>



    </tr>



    <tr>



      <td align="right" bgcolor="#F3F3F3"><strong>*Endereço</strong></td>



      <td bgcolor="#FFFFFF"><span id="sprytextfield6">



        <input type="text" name="endereco" id="endereco" style="width:400px"/>



      <span class="textfieldRequiredMsg">Digite seu endereço.</span></span></td>



    </tr>



    <tr>



      <td align="right" bgcolor="#F3F3F3"><strong>*Número</strong></td>



      <td bgcolor="#FFFFFF"><span id="sprytextfield7">



        <input type="text" name="numero" id="numero" />



      <span class="textfieldRequiredMsg">Digite o número de sua residência ou S/N.</span></span></td>



    </tr>



    <tr>



      <td align="right" bgcolor="#F3F3F3"><strong>Complemento</strong></td>



      <td bgcolor="#FFFFFF"><input type="text" name="complemento" id="complemento" style="width:400px"/></td>



    </tr>



    <tr>



      <td align="right" bgcolor="#F3F3F3"><strong>*Bairro</strong></td>



      <td bgcolor="#FFFFFF"><span id="sprytextfield8">



        <input type="text" name="bairro" id="bairro" />



      <span class="textfieldRequiredMsg">Digite seu bairro.</span></span></td>



    </tr>



    <tr>



      <td align="right" bgcolor="#F3F3F3"><strong>*Estado</strong></td>



      <td bgcolor="#FFFFFF"><span id="spryselect2">

      <select name="estado" id='estado_cur' onchange="pegarCidades();" help="Selecione o estado em que você reside." class="input">
        <option label="Selecione" value="">Selecione</option>
        <?php foreach ($dados['estados'] as $estado) 
          { 
            echo "<option label='". $estado['estado'] ."' value='". $estado['id'] ."'>". $estado['estado'] ."</option>";
          }
        ?>
      </select>

<span class="selectRequiredMsg">Escolha seu estado.</span></span></td>



    </tr>

    <tr>



      <td align="right" bgcolor="#F3F3F3"><strong>* Cidade</strong></td>



      <td bgcolor="#FFFFFF"><span id="sprytextfield9">


           <select name="cidade" id='cidade' help="Selecione a cidade em que você reside." class="input">
           <option label="" value=""></option>
          </select>
<img hidden id="carregandoCidades" width="30px" style="margin-bottom:-10px;" src="<?php echo URL; ?>public/images/carregando.gif">
          
      <span class="selectRequiredMsg">Escolha sua cidade.</span></span>
  
      </td>



    </tr>


    <tr>



      <td align="right" bgcolor="#F3F3F3"><p><strong>*Telefones para contato: </strong></p>



      <p>(Informe ao menos 1 telefone)</p></td>



      <td bgcolor="#FFFFFF"><table width="100%" border="0">



        <tr>



          <td>Fone 1: </td>



          <td><span id="sprytextfield23">

            <input type="text" name="foneCell" id="foneCell" />

            <span class="textfieldRequiredMsg">Digite pelo menos um telefone de contato.</span></span></td>



          </tr>



        <tr>



          <td>Fone 2: </td>



          <td><input type="text" name="foneFixo" id="foneFixo" /></td>



          </tr>



        <tr>



          <td>Fone 3: </td>



          <td><input type="text" name="foneComercial" id="foneComercial" /></td>



          </tr>



      </table></td>



    </tr>



    <tr>



      <td align="right">&nbsp;</td>



      <td bgcolor="#FFFFFF">&nbsp;</td>



    </tr>



    <tr>



      <td align="right" bgcolor="#F3F3F3"><strong>*Está empregado atualmente?</strong></td>



      <td bgcolor="#FFFFFF"><label for="empregado"><span id="spryradio2">



          <input type="radio" name="empregado" value="1" id="empregado_0" />



Sim



<input type="radio" name="empregado" value="0" id="empregado_1" />



Não<br />



<span class="radioRequiredMsg">Diga se você está ou não empregado atualmente</span></span></label></td>



    </tr>

<tr>
<td align="right" bgcolor="#F3F3F3">Possui carteira de motorista?</td>  
<td bgcolor="#FFFFFF"><label for="empregado"><span id="spryradio2">

   <input type="radio" name="habilitacao" value="2" id="habilitacaoSim" />
   Sim
    <input type="radio" name="abilitacao" value="1" id="habilitacaoNao" checked="checked"/>
   Não 
   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
   Categoria:
    <select name="categoria" id="categoria" disabled>
      <option value="" id="categoriaValor"></option>
      <option value="A">A</option>
      <option value="B">B</option>
      <option value="C">C</option>
      <option value="D">D</option>
      <option value="E">E</option>
    </select>
   
</tr>

<tr>
<td align="right" bgcolor="#F3F3F3">Possui alguma deficiência?</td>  
<td bgcolor="#FFFFFF"><label for="empregado"><span id="spryradio2">
  <input type="radio" name="deficiencia" value="1" id="deficienciaSim" />
   Sim
  <input type="radio" name="deficiencia" value="0" id="deficienciaNao" checked="checked"/>
   Não 

   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  Descreva a deficiência
  <input type="text" name="descricaoDeficiencia" id="descricaoDeficiencia" style="width:300px" disabled/>
</tr>  

  </table>



  



  <h2>Interesse Profissional</h2>



  



  <table width="100%" border="0" cellpadding="2" cellspacing="1" class="bloco">



    <tr>



      <td align="right" bgcolor="#F3F3F3"><strong>*Cargo de Interesse</strong></td>



      <td bgcolor="#FFFFFF"><span id="sprytextfield11">



        <!-- <input type="text" name="cargoInteresse" id="cargoInteresse" /> -->
 <select name="cargoInteresse" id="cargoInteresse">

          <option></option>

        <?php 
          echo $cargos;
        ?>

        </select>


      <span class="selectRequiredMsg">Selecione o cargo de interesse.</span></span></td>



    </tr>



    <tr>



      <td align="right">&nbsp;</td>



      <td><label for="nome"></label></td>



    </tr>



    <tr>



      <td colspan="2" bgcolor="#d9e3e8"><strong>*Área profissional desejada (selecione todas as aréas nas quais deseja atuar)</strong></td>
    </tr>
    <tr>
      <td align="right" width="35%">Nível 
        <select name="interNivel1" id="interNivel1" onchange="nivel()">
          <option value="">Selecione uma opção</option>
          <option value="Primeiro Emprego">Primeiro Emprego</option>
          <?php echo $niveis; ?>
        </select>
      </td>
      <td>
        &nbsp;&nbsp;&nbsp;&nbsp;Segmento
        <select name="interSegmento1">
          <option value="">Selecione uma opção</option>
          <?php echo $segmentos; ?>
          </select>  
      </td>
    </tr>

    <tr>
      <td align="right" width="35%">Nível 
        <select name="interNivel2">
          <option value="">Selecione uma opção</option>
          <?php echo $niveis; ?>
        </select>
      </td>
      <td>
        &nbsp;&nbsp;&nbsp;&nbsp;Segmento
        <select name="interSegmento2">
          <option value="">Selecione uma opção</option><?php echo $segmentos; ?></select>  
      </td>
    </tr>  

    <tr>
      <td align="right" width="35%">Nível 
        <select name="interNivel3">
          <option value="">Selecione uma opção</option>
          <?php echo $niveis; ?>
        </select>
      </td>
      <td>
        &nbsp;&nbsp;&nbsp;&nbsp;Segmento
        <select name="interSegmento3">
          <option value="">Selecione uma opção</option><?php echo $segmentos; ?></select>  
      </td>
    </tr>      


    <tr>



      <td align="right">&nbsp;</td>



      <td>&nbsp;</td>



    </tr>



    <tr>



      <td align="right" bgcolor="#F3F3F3"><strong>*Pretensão Salarial:</strong></td>



      <td bgcolor="#FFFFFF"><span id="sprytextfield12">



        <input type="text" name="pretensaoSalarial" class="moeda" id="pretensaoSalarial" />



      <span class="textfieldRequiredMsg">Digite uma pretensão salarial</span></span> (estimativa)</td>



    </tr>



  </table>



  



  



  <h2>Experiência profissonal</h2>



  



  <table width="100%" border="0" cellpadding="2" cellspacing="1" class="bloco">



    <tr>



      <td colspan="2" bgcolor="#d9e3e8"><strong>Última experiência/Experiência Atual</strong></td>



    </tr>

    <tr>
      <td align="right" width="35%">Nível 
        <select name="expNivel1" id="expNivel1">
          <option value="">Selecione uma opção</option>
          <?php echo $niveis; ?>
        </select>
      </td>
      <td>
        &nbsp;&nbsp;&nbsp;&nbsp;Segmento
        <select name="expSegmento1" id="expSegmento1">
          <option value="">Selecione uma opção</option><?php echo $segmentos; ?></select>  
      </td>
    </tr> 

    <tr>
      <td align="right" bgcolor="#F3F3F3"> Empresa:</td>
      <td bgcolor="#FFFFFF">
        <span id="sprytextfield50">
          <input type="text" name="expNomeDaEmpresa" id="expNomeDaEmpresa" style="width:405px" onchange="setObrigatorioDatas1();"/>
          <span class="textfieldRequiredMsg"><br>Adicione alguma experiência profissional.</span>
          <span class="textfieldInvalidFormatMsg"><br>Adicione alguma experiência profissional.</span>
        </span>          
     </td>



    </tr>

    <tr>



      <td align="right" bgcolor="#F3F3F3">Último cargo:</td>



      <td bgcolor="#FFFFFF"><input type="text" name="expCargo" id="expCargo" /></td>



    </tr>

    <tr>
      <td align="right" bgcolor="#F3F3F3">Período:</td>
      <td bgcolor="#FFFFFF">
    <span id="sprytextfield30">
        &nbsp;&nbsp;Início <input type="text" name="expInicio1" id="expInicio1" onkeyup="DigitaData(this)" onblur="DigitaData(this)" /> 
    <span class="textfieldInvalidFormatMsg">Data Inválida.</span><span class="textfieldRequiredMsg">Obrigatório</span></span>
    <span id="sprytextfield31">
        Fim <input type="text" name="expFim1" id="expFim1" onkeyup="DigitaData(this)" onblur="DigitaData(this)" />
    <span class="textfieldInvalidFormatMsg">Data Inválida.</span><span class="textfieldRequiredMsg">Obrigatório</span></span>   
      </td>    
    </tr>

    <tr>



      <td align="right" bgcolor="#F3F3F3">Último salário:</td>



      <td bgcolor="#FFFFFF"><strong>R$:</strong>



        <input name="expUltimoSalarioInt" class="moeda" type="text" id="expUltimoSalarioInt" size="8" />


</td>



    </tr>



    <tr>



      <td width="322" align="right" bgcolor="#F3F3F3">Atribuições e realizações na empresa:</td>



      <td bgcolor="#FFFFFF"><label for="expAtribuicoes2"></label>



      <textarea name="expAtribuicoes" id="expAtribuicoes" cols="70" rows="7"></textarea></td>



    </tr>



    <tr>



      <td align="right">&nbsp;</td>



      <td>&nbsp;</td>



    </tr>

 
   <tr>



      <td colspan="2" bgcolor="#d9e3e8"><strong>Outra Experiência</strong></td>



    </tr>

    <tr>
      <td align="right" width="35%">Nível 
        <select name="expNivel2" id="expNivel2">
          <option value="">Selecione uma opção</option>
          <?php echo $niveis; ?>
        </select>
      </td>
      <td>
        &nbsp;&nbsp;&nbsp;&nbsp;Segmento
        <select name="expSegmento2" id="expSegmento2">
          <option value="">Selecione uma opção</option><?php echo $segmentos; ?></select>  
      </td>
    </tr>

    <tr>



      <td align="right" bgcolor="#F3F3F3">Empresa:</td>



      <td bgcolor="#FFFFFF"><input type="text" name="expNomeDaEmpresa2" id="expNomeDaEmpresa2" onchange="setObrigatorioDatas2()" style="width:405px" /></td>



    </tr>



    <tr>



      <td align="right" bgcolor="#F3F3F3">Último cargo:</td>



      <td bgcolor="#FFFFFF"><input type="text" name="expCargo2" id="expCargo2" /></td>



    </tr>
    <tr>
      <td align="right" bgcolor="#F3F3F3">Período:</td>
      <td bgcolor="#FFFFFF">
      <span id="sprytextfield40">
        &nbsp;&nbsp;Início <input type="text" name="expInicio2" id="expInicio2" onkeyup="DigitaData(this)" onblur="DigitaData(this)" />
      <span class="textfieldInvalidFormatMsg">Data Inválida.</span><span class="textfieldRequiredMsg">Obrigatório</span></span>
      <span id="sprytextfield32">
         Fim <input type="text" name="expFim2" id="expFim2" onkeyup="DigitaData(this)" onblur="DigitaData(this)" />
      <span class="textfieldInvalidFormatMsg">Data Inválida.</span><span class="textfieldRequiredMsg">Obrigatório</span></span>
       </td>
    </tr>


    <tr>



      <td align="right" bgcolor="#F3F3F3">Último salário:</td>



      <td bgcolor="#FFFFFF"><strong>R$:</strong>



        <input name="expUltimoSalarioInt2" class="moeda" type="text" id="expUltimoSalarioInt2" size="8" />


</td>



    </tr>



    <tr>



      <td align="right" bgcolor="#F3F3F3">Atribuições e realizações na empresa:</td>



      <td bgcolor="#FFFFFF"><label for="expAtribuicoes2"></label>



      <textarea name="expAtribuicoes2" id="expAtribuicoes2" cols="70" rows="7"></textarea></td>



    </tr>



    <tr>



      <td align="right">&nbsp;</td>



      <td>&nbsp;</td>



    </tr>


    <tr>
      <td colspan="2" bgcolor="#d9e3e8"><strong>Outra Experiência</strong></td>
    </tr>
    <tr>
      <td align="right" width="35%">Nível 
        <select name="expNivel3" id="expNivel3">
          <option value="">Selecione uma opção</option>
          <?php echo $niveis; ?>
        </select>
      </td>
      <td>
        &nbsp;&nbsp;&nbsp;&nbsp;Segmento
        <select name="expSegmento3" id="expSegmento3">
          <option value="">Selecione uma opção</option><?php echo $segmentos; ?></select>  
      </td>
    </tr>
    <tr>
      <td align="right" bgcolor="#F3F3F3">Empresa:</td>
      <td bgcolor="#FFFFFF"><input type="text" name="expNomeEmpresa3" onchange="setObrigatorioDatas3()" id="expNomeEmpresa3" style="width:405px" /></td>
    </tr>
    <tr>
      <td align="right" bgcolor="#F3F3F3">Último cargo:</td>
      <td bgcolor="#FFFFFF"><input type="text" name="expCargo3" id="expCargo3" /></td>
    </tr>
    <tr>
      <td align="right" bgcolor="#F3F3F3">Período:</td>
   
      <td bgcolor="#FFFFFF">
      <span id="sprytextfield33">
        &nbsp;&nbsp;Início <input type="text" name="expInicio3" id="expInicio3" onkeyup="DigitaData(this)" onblur="DigitaData(this)" />
      <span class="textfieldInvalidFormatMsg">Data Inválida.</span><span class="textfieldRequiredMsg">Obrigatório</span></span>
      <span id="sprytextfield34">
         Fim <input type="text" name="expFim3" id="expFim3" onkeyup="DigitaData(this)" onblur="DigitaData(this)" />
       <span class="textfieldInvalidFormatMsg">Data Inválida.</span><span class="textfieldRequiredMsg">Obrigatório</span></span>
       </td>
    </tr>
    <tr>
      <td align="right" bgcolor="#F3F3F3">Último salário:</td>
      <td bgcolor="#FFFFFF"><strong>R$:</strong>
        <input name="expUltimoSalarioInt3" class="moeda" type="text" id="expUltimoSalarioInt3" size="8" /></td>
    </tr>
    <tr>
      <td align="right" bgcolor="#F3F3F3">Atribuições e realizações na empresa:</td>
      <td bgcolor="#FFFFFF"><label for="expAtribuicoes2"></label>
      <textarea name="expAtribuicoes3" id="expAtribuicoes3" cols="70" rows="7"></textarea></td>
    </tr>
    <tr>
      <td align="right">&nbsp;</td>
      <td>&nbsp;</td>
    </tr>

<!-- 4 -->

    <tr>
      <td colspan="2" bgcolor="#d9e3e8"><strong>Outra Experiência</strong></td>
    </tr>
    <tr>
      <td align="right" width="35%">Nível 
        <select name="expNivel4" id="expNivel4">
          <option value="">Selecione uma opção</option>
          <?php echo $niveis; ?>
        </select>
      </td>
      <td>
        &nbsp;&nbsp;&nbsp;&nbsp;Segmento
        <select name="expSegmento4" id="expSegmento4">
          <option value="">Selecione uma opção</option><?php echo $segmentos; ?></select>  
      </td>
    </tr>
    <tr>
      <td align="right" bgcolor="#F3F3F3">Empresa:</td>
      <td bgcolor="#FFFFFF"><input type="text" name="expNomeEmpresa4" onchange="setObrigatorioDatas4()" id="expNomeEmpresa4" style="width:405px" /></td>
    </tr>
    <tr>
      <td align="right" bgcolor="#F3F3F3">Último cargo:</td>
      <td bgcolor="#FFFFFF"><input type="text" name="expCargo4" id="expCargo4" /></td>
    </tr>
    <tr> 
      <td align="right" bgcolor="#F3F3F3">Período:</td>
      <td bgcolor="#FFFFFF">
      <span id="sprytextfield36">
        &nbsp;&nbsp;Início <input type="text" name="expInicio4" id="expInicio4" onkeyup="DigitaData(this)" onblur="DigitaData(this)" />
      <span class="textfieldInvalidFormatMsg">Data Inválida.</span><span class="textfieldRequiredMsg">Obrigatório</span></span>
      <span id="sprytextfield37">
         Fim <input type="text" name="expFim4" id="expFim4" onkeyup="DigitaData(this)" onblur="DigitaData(this)" />
      <span class="textfieldInvalidFormatMsg">Data Inválida.</span><span class="textfieldRequiredMsg">Obrigatório</span></span>
       </td>
    </tr>
    <tr>
      <td align="right" bgcolor="#F3F3F3">Último salário:</td>
      <td bgcolor="#FFFFFF"><strong>R$:</strong>
        <input name="expUltimoSalarioInt4" class="moeda" type="text" id="expUltimoSalarioInt4" size="8" />
    </tr>
    <tr>
      <td align="right" bgcolor="#F3F3F3">Atribuições e realizações na empresa:</td>
      <td bgcolor="#FFFFFF"><label for="expAtribuicoes4"></label>
      <textarea name="expAtribuicoes4" id="expAtribuicoes4" cols="70" rows="7"></textarea></td>
    </tr>
    <tr>
      <td align="right">&nbsp;</td>
      <td>&nbsp;</td>
    </tr>


<!-- 5 -->

    <tr>
      <td colspan="2" bgcolor="#d9e3e8"><strong>Outra Experiência</strong></td>
    </tr>
    <tr>
      <td align="right" width="35%">Nível 
        <select name="expNivel5" id="expNivel5">
          <option value="">Selecione uma opção</option>
          <?php echo $niveis; ?>
        </select>
      </td>
      <td>
        &nbsp;&nbsp;&nbsp;&nbsp;Segmento
        <select name="expSegmento5" id="expSegmento5">
          <option value="">Selecione uma opção</option><?php echo $segmentos; ?></select>  
      </td>
    </tr>
    <tr>
      <td align="right" bgcolor="#F3F3F3">Empresa:</td>
      <td bgcolor="#FFFFFF"><input type="text" onchange="setObrigatorioDatas5()" name="expNomeEmpresa5" id="expNomeEmpresa5" style="width:405px" /></td>
    </tr>
    <tr>
      <td align="right" bgcolor="#F3F3F3">Último cargo:</td>
      <td bgcolor="#FFFFFF"><input type="text" name="expCargo5" id="expCargo5" /></td>
    </tr>
    <tr>    
      <td align="right" bgcolor="#F3F3F3">Período:</td>
      <td bgcolor="#FFFFFF">
        <span id="sprytextfield38">
        &nbsp;&nbsp;Início <input type="text" name="expInicio5" id="expInicio5" onkeyup="DigitaData(this)" onblur="DigitaData(this)" />
        <span class="textfieldInvalidFormatMsg">Data Inválida.</span><span class="textfieldRequiredMsg">Obrigatório</span></span>
        <span id="sprytextfield39">
         Fim <input type="text" name="expFim5" id="expFim5" onkeyup="DigitaData(this)" onblur="DigitaData(this)" />
        <span class="textfieldInvalidFormatMsg">Data Inválida.</span><span class="textfieldRequiredMsg">Obrigatório</span></span> 
       </td>
    </tr>
    <tr>
      <td align="right" bgcolor="#F3F3F3">Último salário:</td>
      <td bgcolor="#FFFFFF"><strong>R$:</strong>
        <input name="expUltimoSalarioInt5" class="moeda" type="text" id="expUltimoSalarioInt5" size="8" /></td>
    </tr>
    <tr>
      <td align="right" bgcolor="#F3F3F3">Atribuições e realizações na empresa:</td>
      <td bgcolor="#FFFFFF"><label for="expAtribuicoes5"></label>
      <textarea name="expAtribuicoes5" id="expAtribuicoes5" cols="70" rows="7"></textarea></td>
    </tr>
    <tr>
      <td align="right">&nbsp;</td>
      <td>&nbsp;</td>
    </tr>


    <tr>



      <td colspan="2" bgcolor="#d9e3e8"><strong>Informações adicionais:</strong></td>



    </tr>



    <tr>



      <td align="right" bgcolor="#F3F3F3">Fale um pouco mais sobre você e sua vida profissional que  considere importante</td>



      <td bgcolor="#FFFFFF"><textarea name="expInformacoes" id="expInformacoes" cols="70" rows="7"></textarea></td>



    </tr>



  </table>



  



  <h2>Formação Acadêmica</h2>



  



  <table width="100%" border="0" cellpadding="2" cellspacing="1" class="bloco">



    <tr>



      <td colspan="2" bgcolor="#d9e3e8"><strong>Última Formação/Formação Atual</strong></td>



    </tr>

    <tr>



      <td align="right" bgcolor="#F3F3F3">Nome do curso:</td>



      <td bgcolor="#FFFFFF"><input type="text" name="escNomeCurso" id="escNomeCurso" style="width:400px"/></td>



    </tr>

    <tr>



      <td width="320" align="right" bgcolor="#F3F3F3">Grau de formação:</td>



      <td width="69%" bgcolor="#FFFFFF"><label for="escGrau"></label>

       

        <select name="escGrau" id="escGrau" help="Selecione o grau do curso que realizou ou está realizando." onchange="liberaareaformacao('escGrau', 'areaformacao')" class="input">



          <option label="Selecione" value="">Selecione</option>



          <?php echo $grauformacao; ?>


          



          </select>    


      </td>



    </tr>


    <tr>



      <td width="320" align="right" bgcolor="#F3F3F3">Área da formação:</td>



      <td width="69%" bgcolor="#FFFFFF"><label for="escGrau"></label>


        <span id="areaformacaoCampo">
          <select name="areaformacao" id="areaformacao" disabled help="Selecione a área do curso que realizou ou está realizando." class="input">



            <option label="Selecione" value="">Selecione</option>



            <?php echo $areasformacao; ?>



            </select>    

         <span class="selectRequiredMsg">Escolha a área da sua formação.</span>
          </span>

      </td>



    </tr>    


    <tr>



      <td align="right" bgcolor="#F3F3F3">Nome da instituição de Ensino</td>



      <td bgcolor="#FFFFFF"><input type="text" name="escNomeInstituicao" id="escNomeInstituicao" style="width:400px"/></td>



    </tr>



    <tr>



      <td align="right" bgcolor="#F3F3F3">Data de início:</td>



      <td bgcolor="#FFFFFF"><span id="sprytextfield17">



        <input type="text" name="escDataInicio" id="escDataInicio" onkeyup="DigitaData(this)" onblur="DigitaData(this)" />



      <span class="textfieldInvalidFormatMsg">Data Inválida.</span></span></td>



    </tr>



    <tr>



      <td align="right" bgcolor="#F3F3F3">Data de conclusão:</td>



      <td bgcolor="#FFFFFF"><span id="sprytextfield18">



      <input type="text" name="escDataConclusao" id="escDataConclusao" onkeyup="DigitaData(this)" onblur="DigitaData(this)" />



<span class="textfieldInvalidFormatMsg">Data Inválida.</span></span></td>



    </tr>



    <tr>



      <td align="right" bgcolor="#F3F3F3">Ano que está cursando:</td>



      <td bgcolor="#FFFFFF">



        <select name="escAno" help="Selecione em que período do curso você está. Ex.: se estiver no 5º semestre, selecione a opção &quot;3º ano&quot;." class="input" id="escAno">



          <option>Selecione</option>



          <option value="1">1º Ano</option>



          <option value="2">2º Ano</option>



          <option value="3">3º Ano</option>



          <option value="4">4º Ano</option>



          <option value="5">5º Ano</option>



          <option value="6">6º Ano</option>

          <option value="7" >Incompleto</option>

          <option value="8" >Já formado</option>



          </select>



        



        



      </td>



    </tr>



    <tr>



      <td align="right">&nbsp;</td>



      <td>&nbsp;</td>



    </tr>



    <tr>



      <td colspan="2" bgcolor="#d9e3e8"><strong>Outra Formação</strong></td>



    </tr>

    <tr>



      <td align="right" bgcolor="#F3F3F3">Nome do curso:</td>



      <td bgcolor="#FFFFFF"><input type="text" name="escNomeCurso2" id="escNomeCurso2" style="width:400px"/></td>



    </tr>

    <tr>



      <td align="right" bgcolor="#F3F3F3">Grau de formação:</td>



      <td bgcolor="#FFFFFF"><label for="escGrau"></label>



        <select name="escGrau2" id="escGrau2" onchange="liberaareaformacao('escGrau2', 'areaformacao2')" help="Selecione o grau do curso que realizou ou está realizando." class="input">



          <option>Selecione</option>



          <?php echo $grauformacao; ?>



      </select></td>



    </tr>


    <tr>
      <td width="320" align="right" bgcolor="#F3F3F3">Área da formação:</td>



      <td width="69%" bgcolor="#FFFFFF"><label for="escGrau"></label>


      <span id="areaformacaoCampo2">
        <select name="areaformacao2" id="areaformacao2" disabled help="Selecione a área do curso que realizou ou está realizando." class="input">



        <option label="Selecione" value="">Selecione</option>



        <?php echo $areasformacao; ?>



        </select>    

        <span class="selectRequiredMsg">Escolha a área da sua formação.</span>
      </span>

      </td>



    </tr> 


    <tr>



      <td align="right" bgcolor="#F3F3F3">Nome da instituição de Ensino</td>



      <td bgcolor="#FFFFFF"><input type="text" name="escNomeInstituicao2" id="escNomeInstituicao2" style="width:400px"/></td>



    </tr>



    <tr>



      <td align="right" bgcolor="#F3F3F3">Data de início:</td>



      <td bgcolor="#FFFFFF"><span id="sprytextfield19">



      <input type="text" name="escDataInicio2" id="escDataInicio2" onkeyup="DigitaData(this)" onblur="DigitaData(this)"/>



<span class="textfieldInvalidFormatMsg">Data Inválida.</span></span></td>



    </tr>



    <tr>



      <td align="right" bgcolor="#F3F3F3">Data de conclusão:</td>



      <td bgcolor="#FFFFFF"><span id="sprytextfield20">



      <input type="text" name="escDataConclusao2" id="escDataConclusao2" onkeyup="DigitaData(this)" onblur="DigitaData(this)" />



<span class="textfieldInvalidFormatMsg">Data Inválida.</span></span></td>



    </tr>



    <tr>



      <td align="right" bgcolor="#F3F3F3">Ano que está cursando:</td>



      <td bgcolor="#FFFFFF"><select name="escAno2" help="Selecione em que período do curso você está. Ex.: se estiver no 5º semestre, selecione a opção &quot;3º ano&quot;." class="input" id="escAno2">



        <option>Selecione</option>



        <option value="1" >1o Ano</option>



        <option value="2" >2o Ano</option>



        <option value="3" >3o Ano</option>



        <option value="4" >4o Ano</option>



        <option value="5" >5o Ano</option>


        <option value="6" >6o Ano</option>

        <option value="7" >Incompleto</option>

        <option value="8" >Já formado</option>



      </select></td>



    </tr>



  </table>



  



  <h2>Idiomas</h2>



  



  <table width="100%" border="0" cellpadding="2" cellspacing="1" class="bloco">



    <tr>



      <td bgcolor="#F3F3F3"><input type="checkbox" name="idiomaIngles" id="idiomaIngles" />



        <label for="idiomaIngles"></label>



      Inglês</td>



      <td bgcolor="#FFFFFF">



        <input type="radio" name="nivelIdiomaIngles" value="3" />



        Básico 



        <input type="radio" name="nivelIdiomaIngles" value="2" />



        Intermediário 



        <input type="radio" name="nivelIdiomaIngles" value="1" />



      Fluente</td>



    </tr>



    <tr>



      <td bgcolor="#F3F3F3"><input type="checkbox" name="idiomaEspanhol" id="idiomaIngles6" />



        <label for="idiomaIngles6"></label>



      Espanhol</td>



      <td bgcolor="#FFFFFF"><input type="radio" name="nivelIdiomaEspanhol" value="3" />



        Básico



        <input type="radio" name="nivelIdiomaEspanhol" value="2" />



        Intermediário



        <input type="radio" name="nivelIdiomaEspanhol" value="1" />



      Fluente</td>



    </tr>



    <tr>



      <td bgcolor="#F3F3F3"><input type="checkbox" name="idiomaFrances" id="idiomaIngles7" />



        <label for="idiomaIngles7"></label>



      Francês</td>



      <td bgcolor="#FFFFFF"><input type="radio" name="nivelIdiomaFrances" value="3" />



        Básico



        <input type="radio" name="nivelIdiomaFrances" value="2" />



        Intermediário



        <input type="radio" name="nivelIdiomaFrances" value="1" />



      Fluente</td>



    </tr>



    <tr>



      <td bgcolor="#F3F3F3"><input type="checkbox" name="idiomaAlemao" id="idiomaIngles8" />



        <label for="idiomaIngles8"></label>



      Alemão</td>



      <td bgcolor="#FFFFFF"><input type="radio" name="nivelIdiomaAlemao" value="3" />



        Básico



        <input type="radio" name="nivelIdiomaAlemao" value="2" />



        Intermediário



        <input type="radio" name="nivelIdiomaAlemao" value="1" />



      Fluente</td>



    </tr>



    <tr>



      <td bgcolor="#F3F3F3"><input type="checkbox" name="idiomaItaliano" id="idiomaItaliano" onclick="x()"/>



        <label for="idiomaIngles9"></label>



      Italiano</td>



      <td bgcolor="#FFFFFF">



        <div id="nivel">    



          <input type="radio" name="nivelIdiomaItaliano" value="3"  id="nivelIdiomaItaliano"/>



          Básico



          <input type="radio" name="nivelIdiomaItaliano" value="2" />



          Intermediário



          <input type="radio" name="nivelIdiomaItaliano" value="1" />



          Fluente



        </div>



      </td>



    </tr>



  </table>  



  



  <h2>Informática</h2>



  <table width="100%" border="0" cellpadding="2" cellspacing="1" class="bloco">



    <tr>



      <td width="57%" bgcolor="#F3F3F3"><input type="checkbox" name="infOffice" id="infOffice" />



        <strong>Pacote Office</strong> (Windows, Word, Excel, Powerpoint)</td>



      <td width="43%" bgcolor="#FFFFFF"><input type="radio" name="nivelInfOffice" value="3" />



        Básico



        <input type="radio" name="nivelInfOffice" value="2" />



        Intermediário



        <input type="radio" name="nivelInfOffice" value="1" />



        Avançado</td>



    </tr>



    <tr>



      <td bgcolor="#F3F3F3"><input type="checkbox" name="infAplGraficas" id="infAplGraficas"  />



        <strong>Aplicativos Gráficos</strong> (Corel, Photoshop, Illustrator)</td>



      <td bgcolor="#FFFFFF"><input type="radio" name="nivelInfAplGraficas" value="3"/>



        Básico



        <input type="radio" name="nivelInfAplGraficas" value="2"/>



        Intermediário



        <input type="radio" name="nivelInfAplGraficas" value="1"/>



        Avançado</td>



    </tr>



    <tr>



      <td bgcolor="#F3F3F3"><input type="checkbox" name="infDes" id="idiomaFraces2" />



        <strong>Desenvolvimento de software</strong> (Programação e Design)</td>



      <td bgcolor="#FFFFFF"><input type="radio" name="nivelInfDes" value="3"/>



        Básico



        <input type="radio" name="nivelInfDes" value="2"/>



        Intermediário



        <input type="radio" name="nivelInfDes" value="1"/>



        Avançado</td>



    </tr>



    <tr>



      <td bgcolor="#F3F3F3"><input type="checkbox" name="infManut" id="infManut"/>



        <strong>Manutenção de computadores e redes</strong></td>



      <td bgcolor="#FFFFFF"><input type="radio" name="nivelInfManut" value="3" />



        Básico



        <input type="radio" name="nivelInfManut" value="2" />



        Intermediário



        <input type="radio" name="nivelInfManut" value="1" />



        Avançado</td>



    </tr>



  </table>



<div style='display:none'>
  <h2>Configuração de Login</h2>



  


  <table width="100%" border="0" cellpadding="2" cellspacing="1" class="bloco">



    <tr>



      <td colspan="2" bgcolor="#d9e3e8"><strong>Dados para utilização do Sistema</strong></td>



    </tr>



    <tr>



      <td align="right" bgcolor="#F3F3F3"><strong>Login/Email:</strong></td>



      <td bgcolor="#FFFFFF"><span id="loginemail">

      <input name="email2" type="text" id="email2" style="width:300px;"/>

      <span class="textfieldRequiredMsg">Digite um email como seu login.</span><span id="mensagemEmail2" class="textfieldInvalidFormatMsg">Formato de email incorreto.</span></span>



      Seu Login é o E-mail acima inserido.</td>



    </tr>



    <tr>



      <td align="right" bgcolor="#F3F3F3"><strong>*Senha:</strong></td>



      <td bgcolor="#FFFFFF"><span id="sprytextfield21">



      <input type="password" name="senha" id="senha" />



      <span class="textfieldRequiredMsg">Digite sua senha.</span><span class="textfieldMinCharsMsg">Sua senha deve conter no mínimo 4 caracteres.</span><span class="textfieldMaxCharsMsg">Sua deve deve conter no máximo 20 caracteres.</span></span></td>



    </tr>



    <tr>



      <td align="right" bgcolor="#F3F3F3"><strong>*Confirmação de senha:</strong></td>



      <td bgcolor="#FFFFFF"><span id="sprytextfield22">



      <input type="password" name="senha2" id="senha2" />



      <span class="textfieldRequiredMsg">Digite sua senha novamente.</span><span class="textfieldMinCharsMsg">Sua senha deve conter no mínimo 4 caracteres.</span><span class="textfieldMaxCharsMsg">Sua senha deve conter no máximo 20 caracteres.</span></span></td>



    </tr>



    <tr>



      <td colspan="2" align="center" bgcolor="#F3F3F3" height="45px;"><div id="retorno"></div></td>



    </tr>



  </table>  
</div>


  



  



  <div class="barra" align="center">

  

  	<div id="verlogin" style="display:none"><a onclick="verificarLogin()"><spam>Clique aqui para verificar disponibilidade de Login</spam></a></div>

	<div id="submit" >

    <input type="submit" name="cadastrar" id="button" value="Cadastrar" onclick="verificaExperiencia()" onMouseOver="verSenha()" />

    <input type="reset" name="apagar" id="button" value="Apagar" />

	</div>

  </div>  



</form>







<script type="text/javascript">

var sprytextfield1 = new Spry.Widget.ValidationTextField("nomecampleto", "none", {validateOn:["blur", "change"]});


//email 1
//var sprytextfield2 = new Spry.Widget.ValidationTextField("sprytextfield2", "email", {validateOn:["blur", "change"]});



//var sprytextfield3 = new Spry.Widget.ValidationTextField("sprytextfield3", "custom", {validation: "teste", validateOn:["blur", "change"], isRequired:true});



var sprytextfield4 = new Spry.Widget.ValidationTextField("sprytextfield4", "date", {format:"dd/mm/yyyy", validateOn:["blur", "change"]});



var spryradio1 = new Spry.Widget.ValidationRadio("spryradio1", {validateOn:["change"]});



var sprytextfield5 = new Spry.Widget.ValidationTextField("sprytextfield5", "none", {validateOn:["blur", "change"]});



var sprytextfield6 = new Spry.Widget.ValidationTextField("sprytextfield6", "none", {validateOn:["blur", "change"]});



var sprytextfield7 = new Spry.Widget.ValidationTextField("sprytextfield7", "none", {validateOn:["blur", "change"]});



var sprytextfield8 = new Spry.Widget.ValidationTextField("sprytextfield8", "none", {validateOn:["blur", "change"]});



//var sprytextfield9 = new Spry.Widget.ValidationTextField("sprytextfield9", "none", {validateOn:["blur", "change"]});



var spryradio2 = new Spry.Widget.ValidationRadio("spryradio2", {validateOn:["blur", "change"]});



//var sprytextfield11 = new Spry.Widget.ValidationTextField("sprytextfield11", "none", {validateOn:["blur", "change"]});
var spryselect1 = new Spry.Widget.ValidationSelect("sprytextfield11", {validateOn:["change", "blur"]});


var sprytextfield12 = new Spry.Widget.ValidationTextField("sprytextfield12", "none", {validateOn:["blur", "change"]});



var sprytextfield14 = new Spry.Widget.ValidationTextField("sprytextfield14", "none", {validateOn:["blur", "change"], isRequired:false});



var sprytextfield16 = new Spry.Widget.ValidationTextField("sprytextfield16", "none", {isRequired:false, validateOn:["blur", "change"]});



var sprytextfield17 = new Spry.Widget.ValidationTextField("sprytextfield17", "date", {validateOn:["blur", "change"], isRequired:false, format:"dd/mm/yyyy"});



var sprytextfield18 = new Spry.Widget.ValidationTextField("sprytextfield18", "date", {format:"dd/mm/yyyy", validateOn:["blur", "change"], isRequired:false});



var sprytextfield19 = new Spry.Widget.ValidationTextField("sprytextfield19", "date", {format:"dd/mm/yyyy", validateOn:["blur", "change"], isRequired:false});



var sprytextfield20 = new Spry.Widget.ValidationTextField("sprytextfield20", "date", {format:"dd/mm/yyyy", validateOn:["blur", "change"], isRequired:false});



//var sprytextfield21 = new Spry.Widget.ValidationTextField("sprytextfield21", "none", {minChars:4, maxChars:20, validateOn:["change"]});



//var sprytextfield22 = new Spry.Widget.ValidationTextField("sprytextfield22", "none", {minChars:4, maxChars:20, validateOn:["change"]});

var sprytextfield23 = new Spry.Widget.ValidationTextField("sprytextfield23", "none", {validateOn:["blur", "change"]});

var spryselect1 = new Spry.Widget.ValidationSelect("spryselect1", {validateOn:["change", "blur"]});

//var sprytextfield24 = new Spry.Widget.ValidationTextField("sprytextfield24", "email", {validateOn:["blur", "change"]}); 

var spryselect2 = new Spry.Widget.ValidationSelect("spryselect2", {validateOn:["change", "blur"]});

var spryselect2 = new Spry.Widget.ValidationSelect("sprytextfield9", {validateOn:["change", "blur"]});

var sprytextfield30 = new Spry.Widget.ValidationTextField("sprytextfield30", "date", {format:"dd/mm/yyyy", validateOn:["blur", "change"], isRequired:false});

var sprytextfield31 = new Spry.Widget.ValidationTextField("sprytextfield31", "date", {format:"dd/mm/yyyy", validateOn:["blur", "change"], isRequired:false});

var sprytextfield32 = new Spry.Widget.ValidationTextField("sprytextfield32", "date", {format:"dd/mm/yyyy", validateOn:["blur", "change"], isRequired:false});

var sprytextfield33 = new Spry.Widget.ValidationTextField("sprytextfield33", "date", {format:"dd/mm/yyyy", validateOn:["blur", "change"], isRequired:false});

var sprytextfield34 = new Spry.Widget.ValidationTextField("sprytextfield34", "date", {format:"dd/mm/yyyy", validateOn:["blur", "change"], isRequired:false});

var sprytextfield35 = new Spry.Widget.ValidationTextField("sprytextfield35", "date", {format:"dd/mm/yyyy", validateOn:["blur", "change"], isRequired:false});

var sprytextfield36 = new Spry.Widget.ValidationTextField("sprytextfield36", "date", {format:"dd/mm/yyyy", validateOn:["blur", "change"], isRequired:false});

var sprytextfield37 = new Spry.Widget.ValidationTextField("sprytextfield37", "date", {format:"dd/mm/yyyy", validateOn:["blur", "change"], isRequired:false});

var sprytextfield38 = new Spry.Widget.ValidationTextField("sprytextfield38", "date", {format:"dd/mm/yyyy", validateOn:["blur", "change"], isRequired:false});

var sprytextfield39 = new Spry.Widget.ValidationTextField("sprytextfield39", "date", {format:"dd/mm/yyyy", validateOn:["blur", "change"], isRequired:false});

var sprytextfield40 = new Spry.Widget.ValidationTextField("sprytextfield40", "date", {format:"dd/mm/yyyy", validateOn:["blur", "change"], isRequired:false});

var spryselect41 = new Spry.Widget.ValidationSelect("quantidadeFilhos", {validateOn:["change", "blur"]});

var sprytextfield43 = new Spry.Widget.ValidationTextField("sprytextfield3", "custom", {validation: "teste", validateOn:["blur", "change"]});

var sprytextfield50 = new Spry.Widget.ValidationTextField("sprytextfield50", "custom", {validation: "experiencia", validateOn:["blur", "change"]});

//var sprytextfield60 = new Spry.Widget.ValidationTextField("facebook", "custom", {validation: "facebook", validateOn:["blur", "change"], isRequired:false});

var sprytextfield61 = new Spry.Widget.ValidationTextField("sprytextfield2", "custom", {validation: "loginemail", validateOn:["blur"], isRequired:true});

//var sprytextfield2 = new Spry.Widget.ValidationTextField("sprytextfield2", "custom", {validation: "loginemail1", validateOn:["blur"], isRequired:true});

var spryRG = new Spry.Widget.ValidationTextField("rgSpan", "none", {validateOn:["blur", "change"]});

var spryMae = new Spry.Widget.ValidationTextField("nomeMae", "none", {validateOn:["blur", "change"]});

//area da formacao
var areadaformacao = new Spry.Widget.ValidationSelect("areaformacaoCampo", {validateOn:["change", "blur"], isRequired:false});

var areadaformacao2 = new Spry.Widget.ValidationSelect("areaformacaoCampo2", {validateOn:["change", "blur"], isRequired:false});

</script> 
 
    
<div class="clear"></div>
</div>

<div class="bottom">
  	﻿<div class="creditos">Copyright Lucrativia 2015 ©, Todos os Direitos Reservados.<br />Developed by C2 Web Soluções</div>
<div class="clear"></div>  

</div>


</body>

</html>