<?php 
  function niveis($dados, $valor)
  {
    campoSelect($dados, 'niveis', 'nivel', $valor);
  }

  function cargos($dados, $valor)
  {
    campoSelect($dados, 'cargos', 'cargo', $valor);
  }

  function segmentos($dados, $valor) 
  {
    campoSelect($dados, 'segmentos', 'segmento', $valor);
  }

  function cidades($dados, $valor)
  {
    campoSelect($dados, 'cidades', 'cidade', $valor);
  }

  function grauformacao($dados, $valor)
  { 
    campoSelect($dados, 'grauformacao', 'grau', $valor);
  }

  function areasformacao($dados, $valor)
  {
    campoSelect($dados, 'areasformacao', 'areaformacao', $valor);
  }  

  function campoSelect($dados, $campo, $indice, $valor)
  {
      $select = '';
      foreach ($dados[$campo] as $camp)
        $select .= ($camp['id'] == $valor)
          ? "<option value='" . $camp['id'] . "' selected>" . $camp[$indice] . '</option>'
          : "<option value='" . $camp['id'] . "'>         " . $camp[$indice] . '</option>';

      echo $select;
  }

/*  

  $niveis = '';
  foreach ($dados['niveis'] as $id => $nivel)
    $niveis .= "<option value='" . $nivel['id'] ."'>" . $nivel['nivel'] . "</option>"; 

  $grauformacao = '';
  foreach ($dados['grauformacao'] as $id => $grau)
    $grauformacao .= "<option value='" . $grau['id'] ."'>" . $grau['grau'] . "</option>";  

  $areasformacao = '';
  foreach ($dados['areasformacao'] as $id => $grau)
    $areasformacao .= "<option value='" . $grau['id'] ."'>" . $grau['areaformacao'] . "</option>";    

  $segmentos = '';
  foreach ($dados['segmentos'] as $id => $segmento)
    $segmentos .= "<option value='" . $segmento['id'] ."'>" . $segmento['segmento'] . "</option>";  

  $cargos = '';
  foreach ($dados['cargos'] as $id => $cargo)
    $cargos .= "<option value='" . $cargo['id'] ."'>" . $cargo['cargo'] . "</option>";  

*/
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<title>Cadastro de Currículos</title>

<link href="<?php echo URL; ?>public/css/estiloNovo.css" rel="stylesheet" type="text/css" />
<link href='http://fonts.googleapis.com/css?family=Alegreya+Sans' rel='stylesheet' type='text/css'>

<link href="<?php echo URL; ?>public/css/estiloPaginaNovo.css" rel="stylesheet" type="text/css" />
<link rel="shortcut icon" href="<?php echo URL; ?>favicon.ico" type="image/x-icon" />

<script src="<?php echo URL; ?>public/js/valid.js"></script>
<script type="text/javascript" src="<?php echo URL; ?>public/js/jquery.js"></script>


<script type="text/javascript">
var URL = '<?php echo URL; ?>';
function confirmar(id) {

  $('.telaConfirma').fadeIn(500);

}



function carregar(acao) {
  if(acao == "abrir"){
    $('.confirmaFundo').fadeIn(500);
  }else{
    $('.telaConfirma').fadeOut(500);
    $('.confirmaFundo').fadeOut(500);
  }
}



$(document).keydown(function(event) { // caso seja precionado ESC chama mostrarLogin('0')
        if (event.keyCode == 27) 
      mostrarLogin('0');
    });



function mostrarLogin(acao){
  if(acao == "1")
    $('.mascara').fadeIn(400);
  else
    $('.mascara').fadeOut(400);
}

</script>

<script type="text/javascript">

function verificarLogin() {
  var x = document.getElementById('email2');
  $.post('verificarLogin.php', { login: x.value },
    function(output) {
      $('#retorno').html(output).fadeIn(1000);
    });

}



function mostrarSubmit() {

  $('#submit').fadeIn(200);

  $('#verlogin').fadeOut(200);

}

function esconderSubmit() {

  /*
  $('#submit').fadeOut(200);

  $('#retorno').fadeOut(200);

  $('#verlogin').fadeIn(200);
  */
}



</script>



</head>

<body>

<!--bloco para confirmação de cadastro de curriculo ou empresa-->


<div class="confirmaFundo" style="display:none"><div id="loading">

</div></div>

<!--bloco para confirmação de cadastro de curriculo ou empresa-->



<div class="topo">
<div class="topoinner">


<div class="menu">
<div class="menuinner">
<a href="<?php echo URL; ?>"><img src="<?php echo URL; ?>public/images/titulo.png" width="344" height="65" border="0" /></a><br />
<div>
<a href="<?php echo URL; ?>">Página Incial&nbsp;&nbsp;|</a><a href="<?php echo URL; ?>comofunciona/">&nbsp;&nbsp;Como Funciona</a>
</div>
</div>
<!--LOGIN-->

<!--FINAL DO LOGIN-->


</div>

</div>
<div class="transparente"></div>
</div>

<div class="sombra"></div>
<div class="conteudo">

  






<script src="<?php echo URL; ?>public/js/SpryAssets/SpryValidationTextField.js" type="text/javascript"></script>
<!-- <script src="<?php echo URL; ?>public/js/jquery.js" type="text/javascript"></script> -->
<script type="text/javascript" src="<?php echo URL; ?>public/js/jquery.maskedinput.min.js"></script>
<!-- <script src="<?php echo URL; ?>public/js/jquery-mask.min.1.6.1.js" type="text/javascript"></script> -->


<script src="<?php echo URL; ?>public/js/novosTratamentos.js" type="text/javascript"></script>


<link href="<?php echo URL; ?>/SpryAssets/SpryValidationTextField.css" rel="stylesheet" type="text/css" />



<script src="<?php echo URL; ?>/SpryAssets/SpryValidationRadio.js" type="text/javascript"></script>

<script src="<?php echo URL; ?>/SpryAssets/SpryValidationSelect.js" type="text/javascript"></script>

<link href="<?php echo URL; ?>/SpryAssets/SpryValidationRadio.css" rel="stylesheet" type="text/css" />



<link href="<?php echo URL; ?>/SpryAssets/SpryValidationSelect.css" rel="stylesheet" type="text/css" />



<script type="text/javascript">

  function clickpasso(passo) {
    window.location.href = '<?php echo URL; ?>curriculos/cadastrar/passo:' + passo;
  } 

  function verSenha(){



    if (document.formCadCurriculo.senha.value != document.formCadCurriculo.senha2.value) {



      alert('As senhas não conferem');  



    }



  }



</script>

<!-- background-color: rgb(104, 120, 136); -->




<style type="text/css">
#menuPassos {
  width: 100%;
  height: 50px;
  border-radius: 20px;
  background-color: rgb(220, 224, 229);

}

.passos {
  float: left;
  width: 150px;
  height: 50px;
  background-color: rgb(190, 194, 198);
  
}

.passos-cor {
  cursor: pointer;
  float: left;
  width: 150px;
  height: 50px;
  background-color: rgb(196, 83, 8);
  
}

.passos-cor:hover {
  color: #fff;
  text-decoration: underline;
}

.passosTexto {
  margin-top: -6px !important;
  text-align: center;
  color: #fff; 
}

.arrow-left {
  float: left;
  margin-left: -35px;  
  width: 0; 
  height: 0; 
  border-top: 25px solid transparent;
  border-bottom: 25px solid transparent;
  border-left: 25px solid rgb(190, 194, 198);
}

.arrow-left-branca {
  float: left;
  margin-left: -30px;
  width: 0; 
  height: 0; 
  border-top: 25px solid transparent;
  border-bottom: 25px solid transparent;
  border-left: 25px solid rgb(202, 205, 209);
}

.arrow-left-cor {
  float: left;
  margin-left: -35px;  
  width: 0; 
  height: 0; 
  border-top: 25px solid transparent;
  border-bottom: 25px solid transparent;
  border-left: 25px solid rgb(196, 83, 8);
}

.arrow-left-branca-cor {
  float: left;
  margin-left: -30px;
  width: 0; 
  height: 0; 
  border-top: 25px solid transparent;
  border-bottom: 25px solid transparent;
  border-left: 25px solid rgb(196, 83, 8);
}

.passoUm {
  border-top-left-radius: 20px;
  border-bottom-left-radius: 20px;

}

.ultimoPasso {
  border-top-right-radius: 20px;
  border-bottom-right-radius: 20px;
  width: 160px;
}

.cor-proximo{
  float: left;
  background-color: rgb(190, 194, 198);
  width: 30px;
  height: 50px;
}

.cor-proximo-cor{
  float: left;
  background-color: rgb(196, 83, 8);
  width: 30px;
  height: 50px;
}
</style>




<div class="barra">

  <h3 id="cadCurriculo">Cadastrando seu Currículo</h3>



</div>

<?php
  $passoMenu = (\Positiv\Sessao::pegar('passo')) ? \Positiv\Sessao::pegar('passo') : 0; 
  $passoAtual = isset($_GET['passo']) ? $_GET['passo'] : 0;
?>
<div id='menuPassos'>

  <div class='passos-cor passoUm' <?php echo ($passoAtual > 1) ? 'onclick="clickpasso(1);"' : ''?>>
    <div class='passosTexto'<?php echo ($passoAtual <= 1) ? "style='text-decoration: underline;'" : ''; ?>><h2>Dados Pessoais</h2></div>
  </div>
  <div class='cor-proximo<?php echo ($passoMenu > 0) ? '-cor' : ''; ?>'></div>
  <div class='arrow-left-branca<?php echo ($passoMenu == 0) ? '-cor' : ''; ?>'></div>
   <div class='arrow-left-cor'></div>  

  <div class='passos<?php echo ($passoMenu >= 1) ? '-cor' : ''; ?>' <?php echo ($passoMenu >= 1 && $passoAtual != 2) ? 'onclick="clickpasso(2);"' : ''?> style='width: 190px;'>
    <div class='passosTexto' <?php echo ($passoAtual == 2) ? "style='text-decoration: underline;'" : ''; ?>><h2>Interesse Profissional</h2></div>
  </div>
  <div class='cor-proximo<?php echo ($passoMenu > 1) ? '-cor' : ''; ?>'></div>
  <div class='arrow-left-branca<?php echo ($passoMenu == 1) ? '-cor' : ''; ?>'></div>
  <div class='arrow-left<?php echo ($passoMenu >= 1) ? '-cor' : ''; ?>'></div>   

  <div class='passos<?php echo ($passoMenu >= 2) ? '-cor' : ''; ?>' <?php echo ($passoMenu >= 2 && $passoAtual != 3) ? 'onclick="clickpasso(3);"' : ''?> style='width: 190px;'>
    <div class='passosTexto' <?php echo ($passoAtual == 3) ? "style='text-decoration: underline;'" : ''; ?>><h2>Experiência Profissional</h2></div>
  </div>
  <div class='cor-proximo<?php echo ($passoMenu > 2) ? '-cor' : ''; ?>'></div>
  <div class='arrow-left-branca<?php echo ($passoMenu == 2) ? '-cor' : ''; ?>'></div>
  <div class='arrow-left<?php echo ($passoMenu >= 2) ? '-cor' : ''; ?>'></div>    

  <div class='passos<?php echo ($passoMenu >= 3) ? '-cor' : ''; ?>' <?php echo ($passoMenu >= 3 && $passoAtual != 4) ? 'onclick="clickpasso(4);"' : ''?> style='width: 170px;'>
    <div class='passosTexto' <?php echo ($passoAtual == 4) ? "style='text-decoration: underline;'" : ''; ?>><h2>Formação Acadêmica</h2></div>
  </div>
  <div class='cor-proximo<?php echo ($passoMenu > 3) ? '-cor' : ''; ?>'></div>
  <div class='arrow-left-branca<?php echo ($passoMenu == 3) ? '-cor' : ''; ?>'></div>
  <div class='arrow-left<?php echo ($passoMenu >= 3) ? '-cor' : ''; ?>'></div>    

  <div class='passos<?php echo ($passoMenu >= 4) ? '-cor' : ''; ?> ultimoPasso' <?php echo ($passoMenu >= 4 && $passoAtual != 5) ? 'onclick="clickpasso(5);"' : ''?>>
    <div class='passosTexto' <?php echo ($passoAtual == 5) ? "style='text-decoration: underline; margin-left:-70px;'" : "style='margin-left:-70px;'"; ?>><h2>Usuário</h2></div>
  </div>

</div>

* Campos de preenchimento obrigatório







<form id="formCadCurriculo" name="formCadCurriculo" method="post" action="" class="formulario" enctype="multipart/form-data">

<?php
  $passo = isset($_GET['passo']) ? (int)$_GET['passo'] : 1;
  $passo = ($passo > 5) ? 5 : $passo;
  
  echo "<input hidden name='passo' value='$passo'/>";
  $view;
  switch ($passo) {
    case 1:
      $view = 'dados_pessoais';
      break;
    
    case 2:
      $view = 'interesse_profissional';
      break;    

    case 3:
      $view = 'experiencia';
      break;    

    case 4:
      $view = 'escolaridade';
      break;        

    case 5:
      $view = 'configuracao_login';
      break;  

    default:
      $view = 'dados_pessoais';
      break;
  }

  echo "<input type='text' name='passo' value='$passo' hidden/>";

  require RAIZ . SEPARADOR . 'visoes' . SEPARADOR . 'curriculos' . SEPARADOR . 'cadastrar' . SEPARADOR . $view . '.phtml'; ?>
  

  <div class="barra" align="center">

  

    <div id="verlogin" style="display:none"><a onclick="verificarLogin()"><spam>Clique aqui para verificar disponibilidade de Login</spam></a></div>

  <div id="submit" >

    <input type="submit" name="cadastrar" id="button" value="Salvar Informações" 
    <?php echo ($passo == 3) ? 'onclick="verificaExperiencia()"' : ''; ?> onMouseOver="verSenha()" />

  </div>

  </div>  



</form>







<script type="text/javascript">

<?php validacoesJs(); ?>


</script> 
 
    
<div class="clear"></div>
</div>

<div class="bottom">
    ﻿<div class="creditos">Copyright Lucrativia 2015 ©, Todos os Direitos Reservados.</div>
<div class="clear"></div>  

</div>


</body>

</html>