<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<title>Currículos - Logado</title>

<link href="<?php echo URL; ?>public/css/estiloNovo.css" rel="stylesheet" type="text/css" />
<link href='http://fonts.googleapis.com/css?family=Alegreya+Sans' rel='stylesheet' type='text/css'>

<link rel="shortcut icon" href="<?php echo URL; ?>favicon.ico" type="image/x-icon" />

<script src="<?php echo URL; ?>public/js/valid.js"></script>
<script type="text/javascript" src="<?php echo URL; ?>public/js/jquery.js"></script>
<script type="text/javascript">

function confirmar(id) {

	$('.telaConfirma').fadeIn(500);

}



function carregar(acao) {
	if(acao == "abrir"){
		$('.confirmaFundo').fadeIn(500);
	}else{
		$('.telaConfirma').fadeOut(500);
		$('.confirmaFundo').fadeOut(500);
	}
}



$(document).keydown(function(event) { // caso seja precionado ESC chama mostrarLogin('0')
        if (event.keyCode == 27) 
			mostrarLogin('0');
    });



function mostrarLogin(acao){
	if(acao == "1")
		$('.mascara').fadeIn(400);
	else
		$('.mascara').fadeOut(400);
}

</script>

<script type="text/javascript">

function verificarLogin() {
	var x = document.getElementById('email2');
	$.post('verificarLogin.php', { login: x.value },
		function(output) {
			$('#retorno').html(output).fadeIn(1000);
		});
}



function mostrarSubmit() {

	$('#submit').fadeIn(200);

	$('#verlogin').fadeOut(200);

}

function esconderSubmit() {

	$('#submit').fadeOut(200);

	$('#retorno').fadeOut(200);

	$('#verlogin').fadeIn(200);

}



</script>



</head>

<body>

<!--bloco para confirmação de cadastro de curriculo ou empresa-->



<div class="topo" style="height:150px;">
<div class="topoinner" style="height:150px;">


<div class="menu">
<div class="menuinner" >
<a href="<?php echo URL; ?>visualizar"><img src="<?php echo URL; ?>public/images/titulo.png" width="344" height="65" border="0" /></a><br />
<div>
<a target="_blank" href="<?php echo URL; ?>curriculos/visualizar">Currículo &nbsp;|&nbsp;</a><a href="<?php echo URL; ?>curriculos/editar"> Atualizar Currículo &nbsp;|</a>
<a href="<?php echo URL; ?>vagas">&nbsp; Vagas</a>
</div>
</div>

<!--LOGIN-->

<script type="text/javascript">

function recuperarSenha() {

	

	$.get('recuperar_senha.php', { email: document.login.login.value },

		function(output) {

			$('#loginDisplay').html(output).fadeOut(10);

			$('#loginDisplay').html(output).fadeIn(1000);

		});

}

</script>

<!--FINAL DO LOGIN-->


</div>
<div style="float:right; margin-top:-23px;"><a style="color: rgb(130, 126, 128);" href="<?php echo URL; ?>login/deslogar"><h2>Deslogar</h2></a></div>
</div>
<div class="transparente" style="margin-top:-170px;"></div>
</div>

<div class="sombra"></div>
<div class="conteudo">

<div class="textos"><a href="<?php echo URL; ?>curriculos/cadastrar"> <h1 id="curriculo">Cadastre seu<br>Currículo</h1></a>A Lucrativia seleciona as melhores pessoas para trabalhar nas melhores empresas de Sobral e região. Aumente suas chances de conseguir um ótimo emprego e cadastre seu currículo agora. Garanta que seus telefones e email estejam atualizados.
</div>

<div class="textos"><a href="?pagina=vagas"> <h1 id="vagas">Vagas de Estágio<br> e Emprego</h1></a>
Confira aqui algumas vagas de estágio e emprego. Algumas empresas preferem não se identificar e outras preferem não divulgar on-line, apenas diretamente pela Lucrativia.
</div>

<div class="textos"><a href="?pagina=cadEmpresa"><h1 id="empresa">Empresa - Anuncie<br>sua vaga</h1></a>
Precisa de pessoas para trabalhar? Anuncie sua vaga de emprego ou estágio gratuitamente. Ao preencher a vaga ela será analisada e uma consultora entrará em contato para maiores detalhes. <!-- Caso queira entrar em contato, ligue para <span>(88) 9767-1722</span>. -->
</div>
<div class="clear"></div>
</div>

<div class="bottom">
  	﻿<div class="creditos">Copyright Lucrativia 2015 ©, Todos os Direitos Reservados.<br />Developed by C2 Web Soluções</div>
<div class="clear"></div>  

</div>


</body>

</html>
