<?php
  function validacoesJs()
  {
?>
var sprytextfield1 = new Spry.Widget.ValidationTextField("nomecampleto", "none", {validateOn:["blur", "change"]});


//email 1
//var sprytextfield2 = new Spry.Widget.ValidationTextField("sprytextfield2", "email", {validateOn:["blur", "change"]});



//var sprytextfield3 = new Spry.Widget.ValidationTextField("sprytextfield3", "custom", {validation: "teste", validateOn:["blur", "change"], isRequired:true});



var sprytextfield4 = new Spry.Widget.ValidationTextField("sprytextfield4", "date", {format:"dd/mm/yyyy", validateOn:["blur", "change"]});



var spryradio1 = new Spry.Widget.ValidationRadio("spryradio1", {validateOn:["change"]});



var sprytextfield5 = new Spry.Widget.ValidationTextField("sprytextfield5", "none", {validateOn:["blur", "change"]});



var sprytextfield6 = new Spry.Widget.ValidationTextField("sprytextfield6", "none", {validateOn:["blur", "change"]});



var sprytextfield7 = new Spry.Widget.ValidationTextField("sprytextfield7", "none", {validateOn:["blur", "change"]});



var sprytextfield8 = new Spry.Widget.ValidationTextField("sprytextfield8", "none", {validateOn:["blur", "change"]});



//var sprytextfield9 = new Spry.Widget.ValidationTextField("sprytextfield9", "none", {validateOn:["blur", "change"]});



var spryradio2 = new Spry.Widget.ValidationRadio("spryradio2", {validateOn:["blur", "change"]});



//var sprytextfield11 = new Spry.Widget.ValidationTextField("sprytextfield11", "none", {validateOn:["blur", "change"]});
var spryselect1 = new Spry.Widget.ValidationSelect("sprytextfield11", {validateOn:["change", "blur"]});


var sprytextfield12 = new Spry.Widget.ValidationTextField("sprytextfield12", "none", {validateOn:["blur", "change"]});



var sprytextfield14 = new Spry.Widget.ValidationTextField("sprytextfield14", "none", {validateOn:["blur", "change"], isRequired:false});



var sprytextfield16 = new Spry.Widget.ValidationTextField("sprytextfield16", "none", {isRequired:false, validateOn:["blur", "change"]});



var sprytextfield17 = new Spry.Widget.ValidationTextField("sprytextfield17", "date", {validateOn:["blur", "change"], isRequired:false, format:"dd/mm/yyyy"});



var sprytextfield18 = new Spry.Widget.ValidationTextField("sprytextfield18", "date", {format:"dd/mm/yyyy", validateOn:["blur", "change"], isRequired:false});



var sprytextfield19 = new Spry.Widget.ValidationTextField("sprytextfield19", "date", {format:"dd/mm/yyyy", validateOn:["blur", "change"], isRequired:false});



var sprytextfield20 = new Spry.Widget.ValidationTextField("sprytextfield20", "date", {format:"dd/mm/yyyy", validateOn:["blur", "change"], isRequired:false});



var sprytextfield21 = new Spry.Widget.ValidationTextField("sprytextfield21", "none", {minChars:4, maxChars:20, validateOn:["change"]});



var sprytextfield22 = new Spry.Widget.ValidationTextField("sprytextfield22", "none", {minChars:4, maxChars:20, validateOn:["change"]});

var sprytextfield23 = new Spry.Widget.ValidationTextField("sprytextfield23", "none", {validateOn:["blur", "change"]});

var spryselect1 = new Spry.Widget.ValidationSelect("spryselect1", {validateOn:["change", "blur"]});

//var sprytextfield24 = new Spry.Widget.ValidationTextField("sprytextfield24", "email", {validateOn:["blur", "change"]}); 

var spryselect2 = new Spry.Widget.ValidationSelect("spryselect2", {validateOn:["change", "blur"]});

var spryselect2 = new Spry.Widget.ValidationSelect("sprytextfield9", {validateOn:["change", "blur"]});


var sprytextfield30 = new Spry.Widget.ValidationTextField("sprytextfield30", "date", {format:"dd/mm/yyyy", validateOn:["blur", "change"], isRequired:false});

var sprytextfield31 = new Spry.Widget.ValidationTextField("sprytextfield31", "date", {format:"dd/mm/yyyy", validateOn:["blur", "change"], isRequired:false});

var sprytextfield32 = new Spry.Widget.ValidationTextField("sprytextfield32", "date", {format:"dd/mm/yyyy", validateOn:["blur", "change"], isRequired:false});

var sprytextfield33 = new Spry.Widget.ValidationTextField("sprytextfield33", "date", {format:"dd/mm/yyyy", validateOn:["blur", "change"], isRequired:false});

var sprytextfield34 = new Spry.Widget.ValidationTextField("sprytextfield34", "date", {format:"dd/mm/yyyy", validateOn:["blur", "change"], isRequired:false});

var sprytextfield35 = new Spry.Widget.ValidationTextField("sprytextfield35", "date", {format:"dd/mm/yyyy", validateOn:["blur", "change"], isRequired:false});

var sprytextfield36 = new Spry.Widget.ValidationTextField("sprytextfield36", "date", {format:"dd/mm/yyyy", validateOn:["blur", "change"], isRequired:false});

var sprytextfield37 = new Spry.Widget.ValidationTextField("sprytextfield37", "date", {format:"dd/mm/yyyy", validateOn:["blur", "change"], isRequired:false});

var sprytextfield38 = new Spry.Widget.ValidationTextField("sprytextfield38", "date", {format:"dd/mm/yyyy", validateOn:["blur", "change"], isRequired:false});

var sprytextfield39 = new Spry.Widget.ValidationTextField("sprytextfield39", "date", {format:"dd/mm/yyyy", validateOn:["blur", "change"], isRequired:false});

var sprytextfield40 = new Spry.Widget.ValidationTextField("sprytextfield40", "date", {format:"dd/mm/yyyy", validateOn:["blur", "change"], isRequired:false});

var spryselect41 = new Spry.Widget.ValidationSelect("quantidadeFilhos", {validateOn:["change", "blur"]});

var sprytextfield43 = new Spry.Widget.ValidationTextField("sprytextfield3", "custom", {validation: "teste", validateOn:["blur", "change"]});

var sprytextfield50 = new Spry.Widget.ValidationTextField("sprytextfield50", "custom", {validation: "experiencia", validateOn:["blur", "change"]});

//var sprytextfield60 = new Spry.Widget.ValidationTextField("facebook", "custom", {validation: "facebook", validateOn:["blur", "change"], isRequired:false});

var sprytextfield61 = new Spry.Widget.ValidationTextField("loginemail", "custom", {validation: "loginemail", validateOn:["blur"], isRequired:true});

var sprytextfield2 = new Spry.Widget.ValidationTextField("sprytextfield2", "custom", {validation: "loginemail1", validateOn:["blur"], isRequired:true});

var spryRG = new Spry.Widget.ValidationTextField("rgSpan", "none", {validateOn:["blur", "change"]});

var spryMae = new Spry.Widget.ValidationTextField("nomeMae", "none", {validateOn:["blur", "change"]});

//area da formacao
//var areadaformacao = new Spry.Widget.ValidationSelect("areaformacaoCampo", "custom", {validation: "validaareaformacao", validateOn:["change", "blur"], isRequired:true});

//area da formacao
var areadaformacao = new Spry.Widget.ValidationSelect("areaformacaoCampo", {validateOn:["change", "blur"], isRequired:false});

var areadaformacao2 = new Spry.Widget.ValidationSelect("areaformacaoCampo2", {validateOn:["change", "blur"], isRequired:false});
<?php    

  }
?>
<input type='file' name='foto' id='foto' hidden />
  <h2>Experiência profissional</h2>

<?php 
   $nivel = \Positiv\Sessao::pegar('interNivel1'); 
   if($nivel == 'Primeiro Emprego') { 
?>
  <h2>Descelecione a opção 'Primeiro Emprego' em Interesse Profissional para poder inserir experiências de empregos.</h2>
<?php } else { ?>

  <input name="interNivel1" id="interNivel1" value="<?php echo \Positiv\Sessao::pegar('interNivel1'); ?>" hidden/>



  <table width="100%" border="0" cellpadding="2" cellspacing="1" class="bloco">



    <tr>



      <td colspan="2" bgcolor="#d9e3e8"><strong>Última experiência/Experiência Atual</strong></td>



    </tr>

    <tr>
      <td align="right" width="35%">Nível 
        <select name="expNivel1" id="expNivel1">
          <option value="">Selecione uma opção</option>
          <?php niveis($dados, \Positiv\Sessao::pegar('expNivel1')); ?>
        </select>
      </td>
      <td>
        &nbsp;&nbsp;&nbsp;&nbsp;Segmento
        <select name="expSegmento1" id="expSegmento1">
          <option value="">Selecione uma opção</option>
          <?php segmentos($dados, \Positiv\Sessao::pegar('expSegmento1')); ?>
        </select>  
      </td>
    </tr> 

    <tr>
      <td align="right" bgcolor="#F3F3F3"> Empresa:</td>
      <td bgcolor="#FFFFFF">
        <span id="sprytextfield50">
          <input type="text" name="expNomeDaEmpresa" value="<?php echo \Positiv\Sessao::pegar('expNomeDaEmpresa'); ?>" id="expNomeDaEmpresa" style="width:405px" onchange="setObrigatorioDatas1();"/>
          <span class="textfieldRequiredMsg"><br>Adicione alguma experiência profissional.</span>
          <span class="textfieldInvalidFormatMsg"><br>Adicione alguma experiência profissional.</span>
        </span>          
     </td>



    </tr>

    <tr>



      <td align="right" bgcolor="#F3F3F3">Último cargo:</td>



      <td bgcolor="#FFFFFF"><input type="text" name="expCargo" value="<?php echo \Positiv\Sessao::pegar('expCargo'); ?>"  id="expCargo" /></td>



    </tr>

    <tr>
      <td align="right" bgcolor="#F3F3F3">Período:</td>
      <td bgcolor="#FFFFFF">
    <span id="sprytextfield30">
        &nbsp;&nbsp;Início <input type="text" name="expInicio1" value="<?php echo \Positiv\Sessao::pegar('expInicio1'); ?>" id="expInicio1" onkeyup="DigitaData(this)" onblur="DigitaData(this)" /> 
    <span class="textfieldInvalidFormatMsg">Data Inválida.</span><span class="textfieldRequiredMsg">Obrigatório</span></span>
    <span id="sprytextfield31">
        Fim <input type="text" name="expFim1" value="<?php echo \Positiv\Sessao::pegar('expFim1'); ?>"  id="expFim1" onkeyup="DigitaData(this)" onblur="DigitaData(this)" />
    <span class="textfieldInvalidFormatMsg">Data Inválida.</span><span class="textfieldRequiredMsg">Obrigatório</span></span>   
      </td>    
    </tr>

    <tr>



      <td align="right" bgcolor="#F3F3F3">Último salário:</td>



      <td bgcolor="#FFFFFF"><strong>R$:</strong>



        <input name="expUltimoSalarioInt" value="<?php echo \Positiv\Sessao::pegar('expUltimoSalarioInt'); ?>" class="moeda" type="text" id="expUltimoSalarioInt" size="8" />


</td>



    </tr>



    <tr>



      <td width="322" align="right" bgcolor="#F3F3F3">Atribuições e realizações na empresa:</td>



      <td bgcolor="#FFFFFF"><label for="expAtribuicoes2"></label>



      <textarea name="expAtribuicoes" id="expAtribuicoes" cols="70" rows="7"><?php echo \Positiv\Sessao::pegar('expAtribuicoes'); ?></textarea></td>



    </tr>



    <tr>



      <td align="right">&nbsp;</td>



      <td>&nbsp;</td>



    </tr>

 
   <tr>



      <td colspan="2" bgcolor="#d9e3e8"><strong>Outra Experiência</strong></td>



    </tr>

    <tr>
      <td align="right" width="35%">Nível 
        <select name="expNivel2" id="expNivel2">
          <option value="">Selecione uma opção</option>
          <?php niveis($dados, \Positiv\Sessao::pegar('expNivel2')); ?>
        </select>
      </td>
      <td>
        &nbsp;&nbsp;&nbsp;&nbsp;Segmento
        <select name="expSegmento2" id="expSegmento2">
          <option value="">Selecione uma opção</option>
          <?php segmentos($dados, \Positiv\Sessao::pegar('expSegmento2')); ?>
        </select>  
      </td>
    </tr>

    <tr>



      <td align="right" bgcolor="#F3F3F3">Empresa:</td>



      <td bgcolor="#FFFFFF"><input type="text" name="expNomeDaEmpresa2" value="<?php echo \Positiv\Sessao::pegar('expNomeDaEmpresa2'); ?>" id="expNomeDaEmpresa2" onchange="setObrigatorioDatas2()" style="width:405px" /></td>



    </tr>



    <tr>



      <td align="right" bgcolor="#F3F3F3">Último cargo:</td>



      <td bgcolor="#FFFFFF"><input type="text" name="expCargo2" value="<?php echo \Positiv\Sessao::pegar('expCargo2'); ?>" id="expCargo2" /></td>



    </tr>
    <tr>
      <td align="right" bgcolor="#F3F3F3">Período:</td>
      <td bgcolor="#FFFFFF">
      <span id="sprytextfield40">
        &nbsp;&nbsp;Início <input type="text" name="expInicio2" value="<?php echo \Positiv\Sessao::pegar('expInicio2'); ?>" id="expInicio2" onkeyup="DigitaData(this)" onblur="DigitaData(this)" />
      <span class="textfieldInvalidFormatMsg">Data Inválida.</span><span class="textfieldRequiredMsg">Obrigatório</span></span>
      <span id="sprytextfield32">
         Fim <input type="text" name="expFim2" value="<?php echo \Positiv\Sessao::pegar('expFim2'); ?>" id="expFim2" onkeyup="DigitaData(this)" onblur="DigitaData(this)" />
      <span class="textfieldInvalidFormatMsg">Data Inválida.</span><span class="textfieldRequiredMsg">Obrigatório</span></span>
       </td>
    </tr>


    <tr>



      <td align="right" bgcolor="#F3F3F3">Último salário:</td>



      <td bgcolor="#FFFFFF"><strong>R$:</strong>



        <input name="expUltimoSalarioInt2" value="<?php echo \Positiv\Sessao::pegar('expUltimoSalarioInt2'); ?>" class="moeda" type="text" id="expUltimoSalarioInt2" size="8" />


</td>



    </tr>



    <tr>



      <td align="right" bgcolor="#F3F3F3">Atribuições e realizações na empresa:</td>



      <td bgcolor="#FFFFFF"><label for="expAtribuicoes2"></label>



      <textarea name="expAtribuicoes2" id="expAtribuicoes2" cols="70" rows="7"><?php echo \Positiv\Sessao::pegar('expAtribuicoes2'); ?></textarea></td>



    </tr>



    <tr>



      <td align="right">&nbsp;</td>



      <td>&nbsp;</td>



    </tr>


    <tr>
      <td colspan="2" bgcolor="#d9e3e8"><strong>Outra Experiência</strong></td>
    </tr>
    <tr>
      <td align="right" width="35%">Nível 
        <select name="expNivel3" id="expNivel3">
          <option value="">Selecione uma opção</option>
          <?php niveis($dados, \Positiv\Sessao::pegar('expNivel3')); ?>
        </select>
      </td>
      <td>
        &nbsp;&nbsp;&nbsp;&nbsp;Segmento
        <select name="expSegmento3" id="expSegmento3">
          <option value="">Selecione uma opção</option>
          <?php segmentos($dados, \Positiv\Sessao::pegar('expSegmento3')); ?>
        </select>  
      </td>
    </tr>
    <tr>
      <td align="right" bgcolor="#F3F3F3">Empresa:</td>
      <td bgcolor="#FFFFFF"><input type="text" name="expNomeEmpresa3" value="<?php echo \Positiv\Sessao::pegar('expNomeEmpresa3'); ?>" onchange="setObrigatorioDatas3()" id="expNomeEmpresa3" style="width:405px" /></td>
    </tr>
    <tr>
      <td align="right" bgcolor="#F3F3F3">Último cargo:</td>
      <td bgcolor="#FFFFFF"><input type="text" name="expCargo3" value="<?php echo \Positiv\Sessao::pegar('expCargo3'); ?>" id="expCargo3" /></td>
    </tr>
    <tr>
      <td align="right" bgcolor="#F3F3F3">Período:</td>
   
      <td bgcolor="#FFFFFF">
      <span id="sprytextfield33">
        &nbsp;&nbsp;Início <input type="text" name="expInicio3" value="<?php echo \Positiv\Sessao::pegar('expInicio3'); ?>" id="expInicio3" onkeyup="DigitaData(this)" onblur="DigitaData(this)" />
      <span class="textfieldInvalidFormatMsg">Data Inválida.</span><span class="textfieldRequiredMsg">Obrigatório</span></span>
      <span id="sprytextfield34">
         Fim <input type="text" name="expFim3" value="<?php echo \Positiv\Sessao::pegar('expFim3'); ?>" id="expFim3" onkeyup="DigitaData(this)" onblur="DigitaData(this)" />
       <span class="textfieldInvalidFormatMsg">Data Inválida.</span><span class="textfieldRequiredMsg">Obrigatório</span></span>
       </td>
    </tr>
    <tr>
      <td align="right" bgcolor="#F3F3F3">Último salário:</td>
      <td bgcolor="#FFFFFF"><strong>R$:</strong>
        <input name="expUltimoSalarioInt3" value="<?php echo \Positiv\Sessao::pegar('expUltimoSalarioInt3'); ?>" class="moeda" type="text" id="expUltimoSalarioInt3" size="8" /></td>
    </tr>
    <tr>
      <td align="right" bgcolor="#F3F3F3">Atribuições e realizações na empresa:</td>
      <td bgcolor="#FFFFFF"><label for="expAtribuicoes2"></label>
      <textarea name="expAtribuicoes3" id="expAtribuicoes3" cols="70" rows="7"><?php echo \Positiv\Sessao::pegar('expAtribuicoes3'); ?></textarea></td>
    </tr>
    <tr>
      <td align="right">&nbsp;</td>
      <td>&nbsp;</td>
    </tr>

<!-- 4 -->

    <tr>
      <td colspan="2" bgcolor="#d9e3e8"><strong>Outra Experiência</strong></td>
    </tr>
    <tr>
      <td align="right" width="35%">Nível 
        <select name="expNivel4" id="expNivel4">
          <option value="">Selecione uma opção</option>
          <?php niveis($dados, \Positiv\Sessao::pegar('expNivel4')); ?>
        </select>
      </td>
      <td>
        &nbsp;&nbsp;&nbsp;&nbsp;Segmento
        <select name="expSegmento4" id="expSegmento4">
          <option value="">Selecione uma opção</option>
           <?php segmentos($dados, \Positiv\Sessao::pegar('expSegmento4')); ?>
        </select>  
      </td>
    </tr>
    <tr>
      <td align="right" bgcolor="#F3F3F3">Empresa:</td>
      <td bgcolor="#FFFFFF"><input type="text" name="expNomeEmpresa4" value="<?php echo \Positiv\Sessao::pegar('expNomeEmpresa4'); ?>" onchange="setObrigatorioDatas4()" id="expNomeEmpresa4" style="width:405px" /></td>
    </tr>
    <tr>
      <td align="right" bgcolor="#F3F3F3">Último cargo:</td>
      <td bgcolor="#FFFFFF"><input type="text" name="expCargo4" value="<?php echo \Positiv\Sessao::pegar('expCargo4'); ?>" id="expCargo4" /></td>
    </tr>
    <tr> 
      <td align="right" bgcolor="#F3F3F3">Período:</td>
      <td bgcolor="#FFFFFF">
      <span id="sprytextfield36">
        &nbsp;&nbsp;Início <input type="text" name="expInicio4" value="<?php echo \Positiv\Sessao::pegar('expInicio4'); ?>"  id="expInicio4" onkeyup="DigitaData(this)" onblur="DigitaData(this)" />
      <span class="textfieldInvalidFormatMsg">Data Inválida.</span><span class="textfieldRequiredMsg">Obrigatório</span></span>
      <span id="sprytextfield37">
         Fim <input type="text" name="expFim4" value="<?php echo \Positiv\Sessao::pegar('expFim4'); ?>" id="expFim4" onkeyup="DigitaData(this)" onblur="DigitaData(this)" />
      <span class="textfieldInvalidFormatMsg">Data Inválida.</span><span class="textfieldRequiredMsg">Obrigatório</span></span>
       </td>
    </tr>
    <tr>
      <td align="right" bgcolor="#F3F3F3">Último salário:</td>
      <td bgcolor="#FFFFFF"><strong>R$:</strong>
        <input name="expUltimoSalarioInt4" value="<?php echo \Positiv\Sessao::pegar('expUltimoSalarioInt4'); ?>" class="moeda" type="text" id="expUltimoSalarioInt4" size="8" />
    </tr>
    <tr>
      <td align="right" bgcolor="#F3F3F3">Atribuições e realizações na empresa:</td>
      <td bgcolor="#FFFFFF"><label for="expAtribuicoes4"></label>
      <textarea name="expAtribuicoes4" id="expAtribuicoes4" cols="70" rows="7"><?php echo \Positiv\Sessao::pegar('expAtribuicoes4'); ?></textarea></td>
    </tr>
    <tr>
      <td align="right">&nbsp;</td>
      <td>&nbsp;</td>
    </tr>


<!-- 5 -->

    <tr>
      <td colspan="2" bgcolor="#d9e3e8"><strong>Outra Experiência</strong></td>
    </tr>
    <tr>
      <td align="right" width="35%">Nível 
        <select name="expNivel5" id="expNivel5">
          <option value="">Selecione uma opção</option>
          <?php niveis($dados, \Positiv\Sessao::pegar('expNivel5')); ?>
        </select>
      </td>
      <td>
        &nbsp;&nbsp;&nbsp;&nbsp;Segmento
        <select name="expSegmento5" id="expSegmento5">
          <option value="">Selecione uma opção</option>
          <?php segmentos($dados, \Positiv\Sessao::pegar('expSegmento5')); ?>
        </select>  
      </td>
    </tr>
    <tr>
      <td align="right" bgcolor="#F3F3F3">Empresa:</td>
      <td bgcolor="#FFFFFF"><input type="text" onchange="setObrigatorioDatas5()" name="expNomeEmpresa5" 
      value="<?php echo \Positiv\Sessao::pegar('expNomeEmpresa5'); ?>" id="expNomeEmpresa5" style="width:405px" /></td>
    </tr>
    <tr>
      <td align="right" bgcolor="#F3F3F3">Último cargo:</td>
      <td bgcolor="#FFFFFF"><input type="text" name="expCargo5" value="<?php echo \Positiv\Sessao::pegar('expCargo5'); ?>" id="expCargo5" /></td>
    </tr>
    <tr>    
      <td align="right" bgcolor="#F3F3F3">Período:</td>
      <td bgcolor="#FFFFFF">
        <span id="sprytextfield38">
        &nbsp;&nbsp;Início <input type="text" name="expInicio5" value="<?php echo \Positiv\Sessao::pegar('expInicio5'); ?>" id="expInicio5" onkeyup="DigitaData(this)" onblur="DigitaData(this)" />
        <span class="textfieldInvalidFormatMsg">Data Inválida.</span><span class="textfieldRequiredMsg">Obrigatório</span></span>
        <span id="sprytextfield39">
         Fim <input type="text" name="expFim5" value="<?php echo \Positiv\Sessao::pegar('expFim5'); ?>" id="expFim5" onkeyup="DigitaData(this)" onblur="DigitaData(this)" />
        <span class="textfieldInvalidFormatMsg">Data Inválida.</span><span class="textfieldRequiredMsg">Obrigatório</span></span> 
       </td>
    </tr>
    <tr>
      <td align="right" bgcolor="#F3F3F3">Último salário:</td>
      <td bgcolor="#FFFFFF"><strong>R$:</strong>
        <input name="expUltimoSalarioInt5" value="<?php echo \Positiv\Sessao::pegar('expUltimoSalarioInt5'); ?>" class="moeda" type="text" id="expUltimoSalarioInt5" size="8" /></td>
    </tr>
    <tr>
      <td align="right" bgcolor="#F3F3F3">Atribuições e realizações na empresa:</td>
      <td bgcolor="#FFFFFF"><label for="expAtribuicoes5"></label>
      <textarea name="expAtribuicoes5" id="expAtribuicoes5" cols="70" rows="7"><?php echo \Positiv\Sessao::pegar('expAtribuicoes5'); ?></textarea></td>
    </tr>
    <tr>
      <td align="right">&nbsp;</td>
      <td>&nbsp;</td>
    </tr>


    <tr>



      <td colspan="2" bgcolor="#d9e3e8"><strong>Informações adicionais:</strong></td>



    </tr>



    <tr>



      <td align="right" bgcolor="#F3F3F3">Fale um pouco mais sobre você e sua vida profissional que  considere importante</td>



      <td bgcolor="#FFFFFF">
      <textarea name="expInformacoes" id="expInformacoes" cols="70" rows="7"><?php echo \Positiv\Sessao::pegar('expInformacoes'); ?></textarea></td>



    </tr>



  </table>

  <?php } ?>