<?php
  function validacoesJs()
  {
?>
var sprytextfield1 = new Spry.Widget.ValidationTextField("nomecampleto", "none", {validateOn:["blur", "change"]});


//email 1
//var sprytextfield2 = new Spry.Widget.ValidationTextField("sprytextfield2", "email", {validateOn:["blur", "change"]});



//var sprytextfield3 = new Spry.Widget.ValidationTextField("sprytextfield3", "custom", {validation: "teste", validateOn:["blur", "change"], isRequired:true});



var sprytextfield4 = new Spry.Widget.ValidationTextField("sprytextfield4", "date", {format:"dd/mm/yyyy", validateOn:["blur", "change"]});



var spryradio1 = new Spry.Widget.ValidationRadio("spryradio1", {validateOn:["change"]});



var sprytextfield5 = new Spry.Widget.ValidationTextField("sprytextfield5", "none", {validateOn:["blur", "change"]});



var sprytextfield6 = new Spry.Widget.ValidationTextField("sprytextfield6", "none", {validateOn:["blur", "change"]});



var sprytextfield7 = new Spry.Widget.ValidationTextField("sprytextfield7", "none", {validateOn:["blur", "change"]});



var sprytextfield8 = new Spry.Widget.ValidationTextField("sprytextfield8", "none", {validateOn:["blur", "change"]});



//var sprytextfield9 = new Spry.Widget.ValidationTextField("sprytextfield9", "none", {validateOn:["blur", "change"]});



var spryradio2 = new Spry.Widget.ValidationRadio("spryradio2", {validateOn:["blur", "change"]});



//var sprytextfield11 = new Spry.Widget.ValidationTextField("sprytextfield11", "none", {validateOn:["blur", "change"]});
var spryselect1 = new Spry.Widget.ValidationSelect("sprytextfield11", {validateOn:["change", "blur"]});


var sprytextfield12 = new Spry.Widget.ValidationTextField("sprytextfield12", "none", {validateOn:["blur", "change"]});



var sprytextfield14 = new Spry.Widget.ValidationTextField("sprytextfield14", "none", {validateOn:["blur", "change"], isRequired:false});



var sprytextfield16 = new Spry.Widget.ValidationTextField("sprytextfield16", "none", {isRequired:false, validateOn:["blur", "change"]});



var sprytextfield17 = new Spry.Widget.ValidationTextField("sprytextfield17", "date", {validateOn:["blur", "change"], isRequired:false, format:"dd/mm/yyyy"});



var sprytextfield18 = new Spry.Widget.ValidationTextField("sprytextfield18", "date", {format:"dd/mm/yyyy", validateOn:["blur", "change"], isRequired:false});



var sprytextfield19 = new Spry.Widget.ValidationTextField("sprytextfield19", "date", {format:"dd/mm/yyyy", validateOn:["blur", "change"], isRequired:false});



var sprytextfield20 = new Spry.Widget.ValidationTextField("sprytextfield20", "date", {format:"dd/mm/yyyy", validateOn:["blur", "change"], isRequired:false});



var sprytextfield21 = new Spry.Widget.ValidationTextField("sprytextfield21", "none", {minChars:4, maxChars:20, validateOn:["change"]});



var sprytextfield22 = new Spry.Widget.ValidationTextField("sprytextfield22", "none", {minChars:4, maxChars:20, validateOn:["change"]});

var sprytextfield23 = new Spry.Widget.ValidationTextField("sprytextfield23", "none", {validateOn:["blur", "change"]});

var spryselect1 = new Spry.Widget.ValidationSelect("spryselect1", {validateOn:["change", "blur"]});

//var sprytextfield24 = new Spry.Widget.ValidationTextField("sprytextfield24", "email", {validateOn:["blur", "change"]}); 

var spryselect2 = new Spry.Widget.ValidationSelect("spryselect2", {validateOn:["change", "blur"]});

var spryselect2 = new Spry.Widget.ValidationSelect("sprytextfield9", {validateOn:["change", "blur"]});


var sprytextfield30 = new Spry.Widget.ValidationTextField("sprytextfield30", "date", {format:"dd/mm/yyyy", validateOn:["blur", "change"], isRequired:false});

var sprytextfield31 = new Spry.Widget.ValidationTextField("sprytextfield31", "date", {format:"dd/mm/yyyy", validateOn:["blur", "change"], isRequired:false});

var sprytextfield32 = new Spry.Widget.ValidationTextField("sprytextfield32", "date", {format:"dd/mm/yyyy", validateOn:["blur", "change"], isRequired:false});

var sprytextfield33 = new Spry.Widget.ValidationTextField("sprytextfield33", "date", {format:"dd/mm/yyyy", validateOn:["blur", "change"], isRequired:false});

var sprytextfield34 = new Spry.Widget.ValidationTextField("sprytextfield34", "date", {format:"dd/mm/yyyy", validateOn:["blur", "change"], isRequired:false});

var sprytextfield35 = new Spry.Widget.ValidationTextField("sprytextfield35", "date", {format:"dd/mm/yyyy", validateOn:["blur", "change"], isRequired:false});

var sprytextfield36 = new Spry.Widget.ValidationTextField("sprytextfield36", "date", {format:"dd/mm/yyyy", validateOn:["blur", "change"], isRequired:false});

var sprytextfield37 = new Spry.Widget.ValidationTextField("sprytextfield37", "date", {format:"dd/mm/yyyy", validateOn:["blur", "change"], isRequired:false});

var sprytextfield38 = new Spry.Widget.ValidationTextField("sprytextfield38", "date", {format:"dd/mm/yyyy", validateOn:["blur", "change"], isRequired:false});

var sprytextfield39 = new Spry.Widget.ValidationTextField("sprytextfield39", "date", {format:"dd/mm/yyyy", validateOn:["blur", "change"], isRequired:false});

var sprytextfield40 = new Spry.Widget.ValidationTextField("sprytextfield40", "date", {format:"dd/mm/yyyy", validateOn:["blur", "change"], isRequired:false});

var spryselect41 = new Spry.Widget.ValidationSelect("quantidadeFilhos", {validateOn:["change", "blur"]});

var sprytextfield43 = new Spry.Widget.ValidationTextField("sprytextfield3", "custom", {validation: "teste", validateOn:["blur", "change"]});

var sprytextfield50 = new Spry.Widget.ValidationTextField("sprytextfield50", "custom", {validation: "experiencia", validateOn:["blur", "change"]});

//var sprytextfield60 = new Spry.Widget.ValidationTextField("facebook", "custom", {validation: "facebook", validateOn:["blur", "change"], isRequired:false});

var sprytextfield61 = new Spry.Widget.ValidationTextField("loginemail", "custom", {validation: "loginemail", validateOn:["blur"], isRequired:true});

var sprytextfield2 = new Spry.Widget.ValidationTextField("sprytextfield2", "custom", {validation: "loginemail1", validateOn:["blur"], isRequired:true});

var spryRG = new Spry.Widget.ValidationTextField("rgSpan", "none", {validateOn:["blur", "change"]});

var spryMae = new Spry.Widget.ValidationTextField("nomeMae", "none", {validateOn:["blur", "change"]});

//area da formacao
//var areadaformacao = new Spry.Widget.ValidationSelect("areaformacaoCampo", "custom", {validation: "validaareaformacao", validateOn:["change", "blur"], isRequired:true});

//area da formacao
var areadaformacao = new Spry.Widget.ValidationSelect("areaformacaoCampo", {validateOn:["change", "blur"], isRequired:false});

var areadaformacao2 = new Spry.Widget.ValidationSelect("areaformacaoCampo2", {validateOn:["change", "blur"], isRequired:false});
<?php    

  }
?>

  <h2>Formação Acadêmica</h2>



  



  <table width="100%" border="0" cellpadding="2" cellspacing="1" class="bloco">



    <tr>



      <td colspan="2" bgcolor="#d9e3e8"><strong>Última Formação/Formação Atual</strong></td>



    </tr>

    <tr>



      <td align="right" bgcolor="#F3F3F3">Nome do curso:</td>



      <td bgcolor="#FFFFFF"><input type="text" name="escNomeCurso" value="<?php echo \Positiv\Sessao::pegar('escNomeCurso'); ?>" id="escNomeCurso" style="width:400px"/></td>



    </tr>

    <tr>



      <td width="320" align="right" bgcolor="#F3F3F3">Grau de formação:</td>



      <td width="69%" bgcolor="#FFFFFF"><label for="escGrau"></label>

       

        <select name="escGrau" id="escGrau" help="Selecione o grau do curso que realizou ou está realizando." onchange="liberaareaformacao('escGrau', 'areaformacao')" class="input">



          <option label="Selecione" value="">Selecione</option>



          <?php grauformacao($dados, \Positiv\Sessao::pegar('escGrau')); ?>


          



          </select>    


      </td>



    </tr>


    <tr>



      <td width="320" align="right" bgcolor="#F3F3F3">Área da formação:</td>



      <td width="69%" bgcolor="#FFFFFF"><label for="escGrau"></label>


        <span id="areaformacaoCampo">
          <select name="areaformacao" id="areaformacao" <?php echo (\Positiv\Sessao::pegar('escGrau') != '6') ? 'disabled' : ''; ?> help="Selecione a área do curso que realizou ou está realizando." class="input">



            <option label="Selecione" value="">Selecione</option>



            <?php areasformacao($dados, \Positiv\Sessao::pegar('areaformacao')); ?>



            </select>    

         <span class="selectRequiredMsg">Escolha a área da sua formação.</span>
          </span>

      </td>



    </tr>    


    <tr>



      <td align="right" bgcolor="#F3F3F3">Nome da instituição de Ensino</td>



      <td bgcolor="#FFFFFF"><input type="text" name="escNomeInstituicao" value="<?php echo \Positiv\Sessao::pegar('escNomeInstituicao'); ?>" id="escNomeInstituicao" style="width:400px"/></td>



    </tr>



    <tr>



      <td align="right" bgcolor="#F3F3F3">Data de início:</td>



      <td bgcolor="#FFFFFF"><span id="sprytextfield17">



        <input type="text" name="escDataInicio" value="<?php echo \Positiv\Sessao::pegar('escDataInicio'); ?>" id="escDataInicio" onkeyup="DigitaData(this)" onblur="DigitaData(this)" />



      <span class="textfieldInvalidFormatMsg">Data Inválida.</span></span></td>



    </tr>



    <tr>



      <td align="right" bgcolor="#F3F3F3">Data de conclusão:</td>



      <td bgcolor="#FFFFFF"><span id="sprytextfield18">



      <input type="text" name="escDataConclusao" value="<?php echo \Positiv\Sessao::pegar('escDataConclusao'); ?>" id="escDataConclusao" onkeyup="DigitaData(this)" onblur="DigitaData(this)" />



<span class="textfieldInvalidFormatMsg">Data Inválida.</span></span></td>



    </tr>



    <tr>



      <td align="right" bgcolor="#F3F3F3">Ano que está cursando:</td>



      <td bgcolor="#FFFFFF">



        <select name="escAno" help="Selecione em que período do curso você está. Ex.: se estiver no 5º semestre, selecione a opção &quot;3º ano&quot;." class="input" id="escAno">



          <option value="">Selecione</option>



          <option value="1" <?php echo (\Positiv\Sessao::pegar('escAno') == '1') ? 'selected' : ''; ?>>1º Ano</option>



          <option value="2" <?php echo (\Positiv\Sessao::pegar('escAno') == '2') ? 'selected' : ''; ?>>2º Ano</option>



          <option value="3" <?php echo (\Positiv\Sessao::pegar('escAno') == '3') ? 'selected' : ''; ?>>3º Ano</option>



          <option value="4" <?php echo (\Positiv\Sessao::pegar('escAno') == '4') ? 'selected' : ''; ?>>4º Ano</option>



          <option value="5" <?php echo (\Positiv\Sessao::pegar('escAno') == '5') ? 'selected' : ''; ?>>5º Ano</option>



          <option value="6" <?php echo (\Positiv\Sessao::pegar('escAno') == '6') ? 'selected' : ''; ?>>6º Ano</option>

          <option value="7" <?php echo (\Positiv\Sessao::pegar('escAno') == '7') ? 'selected' : ''; ?>>Incompleto</option>

          <option value="8" <?php echo (\Positiv\Sessao::pegar('escAno') == '8') ? 'selected' : ''; ?>>Já formado</option>



          </select>



        



        



      </td>



    </tr>



    <tr>



      <td align="right">&nbsp;</td>



      <td>&nbsp;</td>



    </tr>



    <tr>



      <td colspan="2" bgcolor="#d9e3e8"><strong>Outra Formação</strong></td>



    </tr>

    <tr>



      <td align="right" bgcolor="#F3F3F3">Nome do curso:</td>



      <td bgcolor="#FFFFFF"><input type="text" name="escNomeCurso2" value="<?php echo \Positiv\Sessao::pegar('escNomeCurso2'); ?>" id="escNomeCurso2" style="width:400px"/></td>



    </tr>

    <tr>



      <td align="right" bgcolor="#F3F3F3">Grau de formação:</td>



      <td bgcolor="#FFFFFF"><label for="escGrau"></label>



        <select name="escGrau2" id="escGrau2" onchange="liberaareaformacao('escGrau2', 'areaformacao2')" help="Selecione o grau do curso que realizou ou está realizando." class="input">



          <option>Selecione</option>



          <?php grauformacao($dados, \Positiv\Sessao::pegar('escGrau2')); ?>



      </select></td>



    </tr>


    <tr>
      <td width="320" align="right" bgcolor="#F3F3F3">Área da formação:</td>



      <td width="69%" bgcolor="#FFFFFF"><label for="escGrau"></label>


      <span id="areaformacaoCampo2">
        <select name="areaformacao2" id="areaformacao2" <?php echo (\Positiv\Sessao::pegar('escGrau2') != '6') ? 'disabled' : ''; ?> help="Selecione a área do curso que realizou ou está realizando." class="input">



        <option label="Selecione" value="">Selecione</option>



        <?php areasformacao($dados, \Positiv\Sessao::pegar('areaformacao2')); ?>



        </select>    

        <span class="selectRequiredMsg">Escolha a área da sua formação.</span>
      </span>

      </td>



    </tr> 


    <tr>



      <td align="right" bgcolor="#F3F3F3">Nome da instituição de Ensino</td>



      <td bgcolor="#FFFFFF"><input type="text" name="escNomeInstituicao2" value="<?php echo \Positiv\Sessao::pegar('escNomeInstituicao2'); ?>" id="escNomeInstituicao2" style="width:400px"/></td>



    </tr>



    <tr>



      <td align="right" bgcolor="#F3F3F3">Data de início:</td>



      <td bgcolor="#FFFFFF"><span id="sprytextfield19">



      <input type="text" name="escDataInicio2" value="<?php echo \Positiv\Sessao::pegar('escDataInicio2'); ?>" id="escDataInicio2" onkeyup="DigitaData(this)" onblur="DigitaData(this)"/>



<span class="textfieldInvalidFormatMsg">Data Inválida.</span></span></td>



    </tr>



    <tr>



      <td align="right" bgcolor="#F3F3F3">Data de conclusão:</td>



      <td bgcolor="#FFFFFF"><span id="sprytextfield20">



      <input type="text" name="escDataConclusao2" value="<?php echo \Positiv\Sessao::pegar('escDataConclusao2'); ?>" id="escDataConclusao2" onkeyup="DigitaData(this)" onblur="DigitaData(this)" />



<span class="textfieldInvalidFormatMsg">Data Inválida.</span></span></td>



    </tr>



    <tr>



      <td align="right" bgcolor="#F3F3F3">Ano que está cursando:</td>



      <td bgcolor="#FFFFFF"><select name="escAno2" help="Selecione em que período do curso você está. Ex.: se estiver no 5º semestre, selecione a opção &quot;3º ano&quot;." class="input" id="escAno2">



        <option value="">Selecione</option>



          <option value="1" <?php echo (\Positiv\Sessao::pegar('escAno2') == '1') ? 'selected' : ''; ?>>1º Ano</option>



          <option value="2" <?php echo (\Positiv\Sessao::pegar('escAno2') == '2') ? 'selected' : ''; ?>>2º Ano</option>



          <option value="3" <?php echo (\Positiv\Sessao::pegar('escAno2') == '3') ? 'selected' : ''; ?>>3º Ano</option>



          <option value="4" <?php echo (\Positiv\Sessao::pegar('escAno2') == '4') ? 'selected' : ''; ?>>4º Ano</option>



          <option value="5" <?php echo (\Positiv\Sessao::pegar('escAno2') == '5') ? 'selected' : ''; ?>>5º Ano</option>



          <option value="6" <?php echo (\Positiv\Sessao::pegar('escAno2') == '6') ? 'selected' : ''; ?>>6º Ano</option>

          <option value="7" <?php echo (\Positiv\Sessao::pegar('escAno2') == '7') ? 'selected' : ''; ?>>Incompleto</option>

          <option value="8" <?php echo (\Positiv\Sessao::pegar('escAno2') == '8') ? 'selected' : ''; ?>>Já formado</option>



      </select></td>



    </tr>



  </table>



  



  <h2>Idiomas</h2>



  



  <table width="100%" border="0" cellpadding="2" cellspacing="1" class="bloco">



    <tr>



      <td bgcolor="#F3F3F3"><input type="checkbox" name="idiomaIngles" 
      <?php echo (\Positiv\Sessao::pegar('idiomaIngles') != '' && \Positiv\Sessao::pegar('idiomaIngles') != 0) ? 'checked="checked"' : ''; ?> id="idiomaIngles" />



        <label for="idiomaIngles"></label>



      Inglês</td>



      <td bgcolor="#FFFFFF">



        <input type="radio" name="nivelIdiomaIngles" 
        <?php echo (\Positiv\Sessao::pegar('nivelIdiomaIngles') == 3) ? 'checked="checked"' : ''; ?> value="3" />



        Básico 



        <input type="radio" name="nivelIdiomaIngles"
        <?php echo (\Positiv\Sessao::pegar('nivelIdiomaIngles') == 2) ? 'checked="checked"' : ''; ?> value="2" />



        Intermediário 



        <input type="radio" name="nivelIdiomaIngles"
        <?php echo (\Positiv\Sessao::pegar('nivelIdiomaIngles') == 1) ? 'checked="checked"' : ''; ?> value="1" />



      Fluente</td>



    </tr>



    <tr>



      <td bgcolor="#F3F3F3"><input type="checkbox" name="idiomaEspanhol"
      <?php echo (\Positiv\Sessao::pegar('idiomaEspanhol') != '' && \Positiv\Sessao::pegar('idiomaEspanhol') != 0) ? 'checked="checked"' : ''; ?> id="idiomaIngles6" />



        <label for="idiomaIngles6"></label>



      Espanhol</td>



      <td bgcolor="#FFFFFF"><input type="radio" name="nivelIdiomaEspanhol"
      <?php echo (\Positiv\Sessao::pegar('nivelIdiomaEspanhol') == 3) ? 'checked="checked"' : ''; ?> value="3" />



        Básico



        <input type="radio" name="nivelIdiomaEspanhol"
        <?php echo (\Positiv\Sessao::pegar('nivelIdiomaEspanhol') == 2) ? 'checked="checked"' : ''; ?> value="2" />



        Intermediário



        <input type="radio" name="nivelIdiomaEspanhol"
        <?php echo (\Positiv\Sessao::pegar('nivelIdiomaEspanhol') == 1) ? 'checked="checked"' : ''; ?> value="1" />



      Fluente</td>



    </tr>



    <tr>



      <td bgcolor="#F3F3F3"><input type="checkbox" name="idiomaFrances"
      <?php echo (\Positiv\Sessao::pegar('idiomaFrances') != '' && \Positiv\Sessao::pegar('idiomaFrances') != 0) ? 'checked="checked"' : ''; ?>  id="idiomaIngles7" />



        <label for="idiomaIngles7"></label>



      Francês</td>



      <td bgcolor="#FFFFFF"><input type="radio" name="nivelIdiomaFrances"
      <?php echo (\Positiv\Sessao::pegar('nivelIdiomaFrances') == 3) ? 'checked="checked"' : ''; ?> value="3" />



        Básico



        <input type="radio" name="nivelIdiomaFrances"
        <?php echo (\Positiv\Sessao::pegar('nivelIdiomaFrances') == 2) ? 'checked="checked"' : ''; ?> value="2" />



        Intermediário



        <input type="radio" name="nivelIdiomaFrances"
        <?php echo (\Positiv\Sessao::pegar('nivelIdiomaFrances') == 1) ? 'checked="checked"' : ''; ?> value="1" />



      Fluente</td>



    </tr>



    <tr>



      <td bgcolor="#F3F3F3"><input type="checkbox" name="idiomaAlemao"
      <?php echo (\Positiv\Sessao::pegar('idiomaAlemao') != '' && \Positiv\Sessao::pegar('idiomaAlemao') != 0) ? 'checked="checked"' : ''; ?> id="idiomaIngles8" />



        <label for="idiomaIngles8"></label>



      Alemão</td>



      <td bgcolor="#FFFFFF"><input type="radio" name="nivelIdiomaAlemao"
      <?php echo (\Positiv\Sessao::pegar('nivelIdiomaAlemao') == 3) ? 'checked="checked"' : ''; ?> value="3" />



        Básico



        <input type="radio" name="nivelIdiomaAlemao"
        <?php echo (\Positiv\Sessao::pegar('nivelIdiomaAlemao') == 2) ? 'checked="checked"' : ''; ?> value="2" />



        Intermediário



        <input type="radio" name="nivelIdiomaAlemao"
        <?php echo (\Positiv\Sessao::pegar('nivelIdiomaAlemao') == 1) ? 'checked="checked"' : ''; ?> value="1" />



      Fluente</td>



    </tr>



    <tr>



      <td bgcolor="#F3F3F3"><input type="checkbox" name="idiomaItaliano"
      <?php echo (\Positiv\Sessao::pegar('idiomaItaliano') != '' && \Positiv\Sessao::pegar('idiomaItaliano') != 0) ? 'checked="checked"' : ''; ?> id="idiomaItaliano" onclick="x()"/>



        <label for="idiomaIngles9"></label>



      Italiano</td>



      <td bgcolor="#FFFFFF">



        <div id="nivel">    



          <input type="radio" name="nivelIdiomaItaliano"
          <?php echo (\Positiv\Sessao::pegar('nivelIdiomaItaliano') == 3) ? 'checked="checked"' : ''; ?> value="3"  id="nivelIdiomaItaliano"/>



          Básico



          <input type="radio" name="nivelIdiomaItaliano"
          <?php echo (\Positiv\Sessao::pegar('nivelIdiomaItaliano') == 2) ? 'checked="checked"' : ''; ?> value="2" />



          Intermediário



          <input type="radio" name="nivelIdiomaItaliano"
          <?php echo (\Positiv\Sessao::pegar('nivelIdiomaItaliano') == 1) ? 'checked="checked"' : ''; ?> value="1" />



          Fluente



        </div>



      </td>



    </tr>



  </table>  



  



  <h2>Informática</h2>



  <table width="100%" border="0" cellpadding="2" cellspacing="1" class="bloco">



    <tr>



      <td width="57%" bgcolor="#F3F3F3"><input type="checkbox" name="infOffice"
      <?php echo (\Positiv\Sessao::pegar('infOffice') != '' && \Positiv\Sessao::pegar('infOffice') != 0) ? 'checked="checked"' : ''; ?> id="infOffice" />



        <strong>Pacote Office</strong> (Windows, Word, Excel, Powerpoint)</td>



      <td width="43%" bgcolor="#FFFFFF"><input type="radio" name="nivelInfOffice"
      <?php echo (\Positiv\Sessao::pegar('nivelInfOffice') == 3) ? 'checked="checked"' : ''; ?> value="3" />



        Básico



        <input type="radio" name="nivelInfOffice"
        <?php echo (\Positiv\Sessao::pegar('nivelInfOffice') == 2) ? 'checked="checked"' : ''; ?> value="2" />



        Intermediário



        <input type="radio" name="nivelInfOffice"
        <?php echo (\Positiv\Sessao::pegar('nivelInfOffice') == 1) ? 'checked="checked"' : ''; ?> value="1" />



        Avançado</td>



    </tr>



    <tr>



      <td bgcolor="#F3F3F3"><input type="checkbox" name="infAplGraficas"
      <?php echo (\Positiv\Sessao::pegar('infAplGraficas') != '' && \Positiv\Sessao::pegar('infAplGraficas') != 0) ? 'checked="checked"' : ''; ?> id="infAplGraficas"  />



        <strong>Aplicativos Gráficos</strong> (Corel, Photoshop, Illustrator)</td>



      <td bgcolor="#FFFFFF"><input type="radio" name="nivelInfAplGraficas"
      <?php echo (\Positiv\Sessao::pegar('nivelInfAplGraficas') == 3) ? 'checked="checked"' : ''; ?> value="3"/>



        Básico



        <input type="radio" name="nivelInfAplGraficas"
        <?php echo (\Positiv\Sessao::pegar('nivelInfAplGraficas') == 2) ? 'checked="checked"' : ''; ?> value="2"/>



        Intermediário



        <input type="radio" name="nivelInfAplGraficas"
        <?php echo (\Positiv\Sessao::pegar('nivelInfAplGraficas') == 1) ? 'checked="checked"' : ''; ?> value="1"/>



        Avançado</td>



    </tr>



    <tr>



      <td bgcolor="#F3F3F3"><input type="checkbox" name="infDes"
      <?php echo (\Positiv\Sessao::pegar('infDes') != '' && \Positiv\Sessao::pegar('infDes') != 0) ? 'checked="checked"' : ''; ?> id="idiomaFraces2" />



        <strong>Desenvolvimento de software</strong> (Programação e Design)</td>



      <td bgcolor="#FFFFFF"><input type="radio" name="nivelInfDes"
      <?php echo (\Positiv\Sessao::pegar('nivelInfDes') == 3) ? 'checked="checked"' : ''; ?> value="3"/>



        Básico



        <input type="radio" name="nivelInfDes"
        <?php echo (\Positiv\Sessao::pegar('nivelInfDes') == 2) ? 'checked="checked"' : ''; ?> value="2"/>



        Intermediário



        <input type="radio" name="nivelInfDes"
        <?php echo (\Positiv\Sessao::pegar('nivelInfDes') == 1) ? 'checked="checked"' : ''; ?> value="1"/>



        Avançado</td>



    </tr>



    <tr>



      <td bgcolor="#F3F3F3"><input type="checkbox" name="infManut"
      <?php echo (\Positiv\Sessao::pegar('infManut') != '' && \Positiv\Sessao::pegar('infManut') != 0) ? 'checked="checked"' : ''; ?> id="infManut"/>



        <strong>Manutenção de computadores e redes</strong></td>



      <td bgcolor="#FFFFFF"><input type="radio" name="nivelInfManut"
      <?php echo (\Positiv\Sessao::pegar('nivelInfManut') == 3) ? 'checked="checked"' : ''; ?> value="3" />



        Básico



        <input type="radio" name="nivelInfManut"
        <?php echo (\Positiv\Sessao::pegar('nivelInfManut') == 2) ? 'checked="checked"' : ''; ?> value="2" />



        Intermediário



        <input type="radio" name="nivelInfManut"
        <?php echo (\Positiv\Sessao::pegar('nivelInfManut') == 1) ? 'checked="checked"' : ''; ?> value="1" />



        Avançado</td>



    </tr>



  </table>